// Code generated by ent, DO NOT EDIT.

package cardproduct

import (
	"card_manager/api_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldID, id))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldStoreID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldType, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldName, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldPrice, v))
}

// Times applies equality check predicate on the "times" field. It's identical to TimesEQ.
func Times(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldTimes, v))
}

// ValidMonths applies equality check predicate on the "valid_months" field. It's identical to ValidMonthsEQ.
func ValidMonths(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldValidMonths, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldStoreID, vs...))
}

// StoreIDGT applies the GT predicate on the "store_id" field.
func StoreIDGT(v int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldStoreID, v))
}

// StoreIDGTE applies the GTE predicate on the "store_id" field.
func StoreIDGTE(v int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldStoreID, v))
}

// StoreIDLT applies the LT predicate on the "store_id" field.
func StoreIDLT(v int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldStoreID, v))
}

// StoreIDLTE applies the LTE predicate on the "store_id" field.
func StoreIDLTE(v int64) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldStoreID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldContainsFold(FieldType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldContainsFold(FieldName, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldPrice, v))
}

// TimesEQ applies the EQ predicate on the "times" field.
func TimesEQ(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldTimes, v))
}

// TimesNEQ applies the NEQ predicate on the "times" field.
func TimesNEQ(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldTimes, v))
}

// TimesIn applies the In predicate on the "times" field.
func TimesIn(vs ...int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldTimes, vs...))
}

// TimesNotIn applies the NotIn predicate on the "times" field.
func TimesNotIn(vs ...int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldTimes, vs...))
}

// TimesGT applies the GT predicate on the "times" field.
func TimesGT(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldTimes, v))
}

// TimesGTE applies the GTE predicate on the "times" field.
func TimesGTE(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldTimes, v))
}

// TimesLT applies the LT predicate on the "times" field.
func TimesLT(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldTimes, v))
}

// TimesLTE applies the LTE predicate on the "times" field.
func TimesLTE(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldTimes, v))
}

// TimesIsNil applies the IsNil predicate on the "times" field.
func TimesIsNil() predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIsNull(FieldTimes))
}

// TimesNotNil applies the NotNil predicate on the "times" field.
func TimesNotNil() predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotNull(FieldTimes))
}

// ValidMonthsEQ applies the EQ predicate on the "valid_months" field.
func ValidMonthsEQ(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldValidMonths, v))
}

// ValidMonthsNEQ applies the NEQ predicate on the "valid_months" field.
func ValidMonthsNEQ(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldValidMonths, v))
}

// ValidMonthsIn applies the In predicate on the "valid_months" field.
func ValidMonthsIn(vs ...int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldValidMonths, vs...))
}

// ValidMonthsNotIn applies the NotIn predicate on the "valid_months" field.
func ValidMonthsNotIn(vs ...int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldValidMonths, vs...))
}

// ValidMonthsGT applies the GT predicate on the "valid_months" field.
func ValidMonthsGT(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldValidMonths, v))
}

// ValidMonthsGTE applies the GTE predicate on the "valid_months" field.
func ValidMonthsGTE(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldValidMonths, v))
}

// ValidMonthsLT applies the LT predicate on the "valid_months" field.
func ValidMonthsLT(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldValidMonths, v))
}

// ValidMonthsLTE applies the LTE predicate on the "valid_months" field.
func ValidMonthsLTE(v int) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldValidMonths, v))
}

// ValidMonthsIsNil applies the IsNil predicate on the "valid_months" field.
func ValidMonthsIsNil() predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIsNull(FieldValidMonths))
}

// ValidMonthsNotNil applies the NotNil predicate on the "valid_months" field.
func ValidMonthsNotNil() predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotNull(FieldValidMonths))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CardProduct {
	return predicate.CardProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.CardProduct {
	return predicate.CardProduct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.CardProductItem) predicate.CardProduct {
	return predicate.CardProduct(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CardProduct) predicate.CardProduct {
	return predicate.CardProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CardProduct) predicate.CardProduct {
	return predicate.CardProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CardProduct) predicate.CardProduct {
	return predicate.CardProduct(sql.NotPredicates(p))
}
