// Code generated by ent, DO NOT EDIT.

package ledgerentryitem

import (
	"card_manager/api_service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLTE(FieldID, id))
}

// LedgerID applies equality check predicate on the "ledger_id" field. It's identical to LedgerIDEQ.
func LedgerID(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldLedgerID, v))
}

// ItemBalanceID applies equality check predicate on the "item_balance_id" field. It's identical to ItemBalanceIDEQ.
func ItemBalanceID(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldItemBalanceID, v))
}

// ProductItemID applies equality check predicate on the "product_item_id" field. It's identical to ProductItemIDEQ.
func ProductItemID(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldProductItemID, v))
}

// NameSnapshot applies equality check predicate on the "name_snapshot" field. It's identical to NameSnapshotEQ.
func NameSnapshot(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldNameSnapshot, v))
}

// Times applies equality check predicate on the "times" field. It's identical to TimesEQ.
func Times(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldTimes, v))
}

// TimesAfter applies equality check predicate on the "times_after" field. It's identical to TimesAfterEQ.
func TimesAfter(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldTimesAfter, v))
}

// LedgerIDEQ applies the EQ predicate on the "ledger_id" field.
func LedgerIDEQ(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldLedgerID, v))
}

// LedgerIDNEQ applies the NEQ predicate on the "ledger_id" field.
func LedgerIDNEQ(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNEQ(FieldLedgerID, v))
}

// LedgerIDIn applies the In predicate on the "ledger_id" field.
func LedgerIDIn(vs ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldIn(FieldLedgerID, vs...))
}

// LedgerIDNotIn applies the NotIn predicate on the "ledger_id" field.
func LedgerIDNotIn(vs ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNotIn(FieldLedgerID, vs...))
}

// ItemBalanceIDEQ applies the EQ predicate on the "item_balance_id" field.
func ItemBalanceIDEQ(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldItemBalanceID, v))
}

// ItemBalanceIDNEQ applies the NEQ predicate on the "item_balance_id" field.
func ItemBalanceIDNEQ(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNEQ(FieldItemBalanceID, v))
}

// ItemBalanceIDIn applies the In predicate on the "item_balance_id" field.
func ItemBalanceIDIn(vs ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldIn(FieldItemBalanceID, vs...))
}

// ItemBalanceIDNotIn applies the NotIn predicate on the "item_balance_id" field.
func ItemBalanceIDNotIn(vs ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNotIn(FieldItemBalanceID, vs...))
}

// ItemBalanceIDGT applies the GT predicate on the "item_balance_id" field.
func ItemBalanceIDGT(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGT(FieldItemBalanceID, v))
}

// ItemBalanceIDGTE applies the GTE predicate on the "item_balance_id" field.
func ItemBalanceIDGTE(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGTE(FieldItemBalanceID, v))
}

// ItemBalanceIDLT applies the LT predicate on the "item_balance_id" field.
func ItemBalanceIDLT(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLT(FieldItemBalanceID, v))
}

// ItemBalanceIDLTE applies the LTE predicate on the "item_balance_id" field.
func ItemBalanceIDLTE(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLTE(FieldItemBalanceID, v))
}

// ProductItemIDEQ applies the EQ predicate on the "product_item_id" field.
func ProductItemIDEQ(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldProductItemID, v))
}

// ProductItemIDNEQ applies the NEQ predicate on the "product_item_id" field.
func ProductItemIDNEQ(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNEQ(FieldProductItemID, v))
}

// ProductItemIDIn applies the In predicate on the "product_item_id" field.
func ProductItemIDIn(vs ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldIn(FieldProductItemID, vs...))
}

// ProductItemIDNotIn applies the NotIn predicate on the "product_item_id" field.
func ProductItemIDNotIn(vs ...int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNotIn(FieldProductItemID, vs...))
}

// ProductItemIDGT applies the GT predicate on the "product_item_id" field.
func ProductItemIDGT(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGT(FieldProductItemID, v))
}

// ProductItemIDGTE applies the GTE predicate on the "product_item_id" field.
func ProductItemIDGTE(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGTE(FieldProductItemID, v))
}

// ProductItemIDLT applies the LT predicate on the "product_item_id" field.
func ProductItemIDLT(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLT(FieldProductItemID, v))
}

// ProductItemIDLTE applies the LTE predicate on the "product_item_id" field.
func ProductItemIDLTE(v int64) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLTE(FieldProductItemID, v))
}

// NameSnapshotEQ applies the EQ predicate on the "name_snapshot" field.
func NameSnapshotEQ(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldNameSnapshot, v))
}

// NameSnapshotNEQ applies the NEQ predicate on the "name_snapshot" field.
func NameSnapshotNEQ(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNEQ(FieldNameSnapshot, v))
}

// NameSnapshotIn applies the In predicate on the "name_snapshot" field.
func NameSnapshotIn(vs ...string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldIn(FieldNameSnapshot, vs...))
}

// NameSnapshotNotIn applies the NotIn predicate on the "name_snapshot" field.
func NameSnapshotNotIn(vs ...string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNotIn(FieldNameSnapshot, vs...))
}

// NameSnapshotGT applies the GT predicate on the "name_snapshot" field.
func NameSnapshotGT(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGT(FieldNameSnapshot, v))
}

// NameSnapshotGTE applies the GTE predicate on the "name_snapshot" field.
func NameSnapshotGTE(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGTE(FieldNameSnapshot, v))
}

// NameSnapshotLT applies the LT predicate on the "name_snapshot" field.
func NameSnapshotLT(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLT(FieldNameSnapshot, v))
}

// NameSnapshotLTE applies the LTE predicate on the "name_snapshot" field.
func NameSnapshotLTE(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLTE(FieldNameSnapshot, v))
}

// NameSnapshotContains applies the Contains predicate on the "name_snapshot" field.
func NameSnapshotContains(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldContains(FieldNameSnapshot, v))
}

// NameSnapshotHasPrefix applies the HasPrefix predicate on the "name_snapshot" field.
func NameSnapshotHasPrefix(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldHasPrefix(FieldNameSnapshot, v))
}

// NameSnapshotHasSuffix applies the HasSuffix predicate on the "name_snapshot" field.
func NameSnapshotHasSuffix(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldHasSuffix(FieldNameSnapshot, v))
}

// NameSnapshotEqualFold applies the EqualFold predicate on the "name_snapshot" field.
func NameSnapshotEqualFold(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEqualFold(FieldNameSnapshot, v))
}

// NameSnapshotContainsFold applies the ContainsFold predicate on the "name_snapshot" field.
func NameSnapshotContainsFold(v string) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldContainsFold(FieldNameSnapshot, v))
}

// TimesEQ applies the EQ predicate on the "times" field.
func TimesEQ(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldTimes, v))
}

// TimesNEQ applies the NEQ predicate on the "times" field.
func TimesNEQ(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNEQ(FieldTimes, v))
}

// TimesIn applies the In predicate on the "times" field.
func TimesIn(vs ...int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldIn(FieldTimes, vs...))
}

// TimesNotIn applies the NotIn predicate on the "times" field.
func TimesNotIn(vs ...int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNotIn(FieldTimes, vs...))
}

// TimesGT applies the GT predicate on the "times" field.
func TimesGT(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGT(FieldTimes, v))
}

// TimesGTE applies the GTE predicate on the "times" field.
func TimesGTE(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGTE(FieldTimes, v))
}

// TimesLT applies the LT predicate on the "times" field.
func TimesLT(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLT(FieldTimes, v))
}

// TimesLTE applies the LTE predicate on the "times" field.
func TimesLTE(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLTE(FieldTimes, v))
}

// TimesAfterEQ applies the EQ predicate on the "times_after" field.
func TimesAfterEQ(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldEQ(FieldTimesAfter, v))
}

// TimesAfterNEQ applies the NEQ predicate on the "times_after" field.
func TimesAfterNEQ(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNEQ(FieldTimesAfter, v))
}

// TimesAfterIn applies the In predicate on the "times_after" field.
func TimesAfterIn(vs ...int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldIn(FieldTimesAfter, vs...))
}

// TimesAfterNotIn applies the NotIn predicate on the "times_after" field.
func TimesAfterNotIn(vs ...int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldNotIn(FieldTimesAfter, vs...))
}

// TimesAfterGT applies the GT predicate on the "times_after" field.
func TimesAfterGT(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGT(FieldTimesAfter, v))
}

// TimesAfterGTE applies the GTE predicate on the "times_after" field.
func TimesAfterGTE(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldGTE(FieldTimesAfter, v))
}

// TimesAfterLT applies the LT predicate on the "times_after" field.
func TimesAfterLT(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLT(FieldTimesAfter, v))
}

// TimesAfterLTE applies the LTE predicate on the "times_after" field.
func TimesAfterLTE(v int) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.FieldLTE(FieldTimesAfter, v))
}

// HasLedger applies the HasEdge predicate on the "ledger" edge.
func HasLedger() predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LedgerTable, LedgerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerWith applies the HasEdge predicate on the "ledger" edge with a given conditions (other predicates).
func HasLedgerWith(preds ...predicate.LedgerEntry) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(func(s *sql.Selector) {
		step := newLedgerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LedgerEntryItem) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LedgerEntryItem) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LedgerEntryItem) predicate.LedgerEntryItem {
	return predicate.LedgerEntryItem(sql.NotPredicates(p))
}
