// Code generated by ent, DO NOT EDIT.

package membercard

import (
	"card_manager/api_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldID, id))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldStoreID, v))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldMemberID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldProductID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldType, v))
}

// NameSnapshot applies equality check predicate on the "name_snapshot" field. It's identical to NameSnapshotEQ.
func NameSnapshot(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldNameSnapshot, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldBalance, v))
}

// RemainTimes applies equality check predicate on the "remain_times" field. It's identical to RemainTimesEQ.
func RemainTimes(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldRemainTimes, v))
}

// ValidFrom applies equality check predicate on the "valid_from" field. It's identical to ValidFromEQ.
func ValidFrom(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldValidFrom, v))
}

// ValidTo applies equality check predicate on the "valid_to" field. It's identical to ValidToEQ.
func ValidTo(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldValidTo, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldStatus, v))
}

// OpenedBy applies equality check predicate on the "opened_by" field. It's identical to OpenedByEQ.
func OpenedBy(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldOpenedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldStoreID, vs...))
}

// StoreIDGT applies the GT predicate on the "store_id" field.
func StoreIDGT(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldStoreID, v))
}

// StoreIDGTE applies the GTE predicate on the "store_id" field.
func StoreIDGTE(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldStoreID, v))
}

// StoreIDLT applies the LT predicate on the "store_id" field.
func StoreIDLT(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldStoreID, v))
}

// StoreIDLTE applies the LTE predicate on the "store_id" field.
func StoreIDLTE(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldStoreID, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldMemberID, vs...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldProductID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldContainsFold(FieldType, v))
}

// NameSnapshotEQ applies the EQ predicate on the "name_snapshot" field.
func NameSnapshotEQ(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldNameSnapshot, v))
}

// NameSnapshotNEQ applies the NEQ predicate on the "name_snapshot" field.
func NameSnapshotNEQ(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldNameSnapshot, v))
}

// NameSnapshotIn applies the In predicate on the "name_snapshot" field.
func NameSnapshotIn(vs ...string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldNameSnapshot, vs...))
}

// NameSnapshotNotIn applies the NotIn predicate on the "name_snapshot" field.
func NameSnapshotNotIn(vs ...string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldNameSnapshot, vs...))
}

// NameSnapshotGT applies the GT predicate on the "name_snapshot" field.
func NameSnapshotGT(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldNameSnapshot, v))
}

// NameSnapshotGTE applies the GTE predicate on the "name_snapshot" field.
func NameSnapshotGTE(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldNameSnapshot, v))
}

// NameSnapshotLT applies the LT predicate on the "name_snapshot" field.
func NameSnapshotLT(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldNameSnapshot, v))
}

// NameSnapshotLTE applies the LTE predicate on the "name_snapshot" field.
func NameSnapshotLTE(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldNameSnapshot, v))
}

// NameSnapshotContains applies the Contains predicate on the "name_snapshot" field.
func NameSnapshotContains(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldContains(FieldNameSnapshot, v))
}

// NameSnapshotHasPrefix applies the HasPrefix predicate on the "name_snapshot" field.
func NameSnapshotHasPrefix(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldHasPrefix(FieldNameSnapshot, v))
}

// NameSnapshotHasSuffix applies the HasSuffix predicate on the "name_snapshot" field.
func NameSnapshotHasSuffix(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldHasSuffix(FieldNameSnapshot, v))
}

// NameSnapshotEqualFold applies the EqualFold predicate on the "name_snapshot" field.
func NameSnapshotEqualFold(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEqualFold(FieldNameSnapshot, v))
}

// NameSnapshotContainsFold applies the ContainsFold predicate on the "name_snapshot" field.
func NameSnapshotContainsFold(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldContainsFold(FieldNameSnapshot, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldBalance, v))
}

// RemainTimesEQ applies the EQ predicate on the "remain_times" field.
func RemainTimesEQ(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldRemainTimes, v))
}

// RemainTimesNEQ applies the NEQ predicate on the "remain_times" field.
func RemainTimesNEQ(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldRemainTimes, v))
}

// RemainTimesIn applies the In predicate on the "remain_times" field.
func RemainTimesIn(vs ...int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldRemainTimes, vs...))
}

// RemainTimesNotIn applies the NotIn predicate on the "remain_times" field.
func RemainTimesNotIn(vs ...int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldRemainTimes, vs...))
}

// RemainTimesGT applies the GT predicate on the "remain_times" field.
func RemainTimesGT(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldRemainTimes, v))
}

// RemainTimesGTE applies the GTE predicate on the "remain_times" field.
func RemainTimesGTE(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldRemainTimes, v))
}

// RemainTimesLT applies the LT predicate on the "remain_times" field.
func RemainTimesLT(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldRemainTimes, v))
}

// RemainTimesLTE applies the LTE predicate on the "remain_times" field.
func RemainTimesLTE(v int) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldRemainTimes, v))
}

// RemainTimesIsNil applies the IsNil predicate on the "remain_times" field.
func RemainTimesIsNil() predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIsNull(FieldRemainTimes))
}

// RemainTimesNotNil applies the NotNil predicate on the "remain_times" field.
func RemainTimesNotNil() predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotNull(FieldRemainTimes))
}

// ValidFromEQ applies the EQ predicate on the "valid_from" field.
func ValidFromEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldValidFrom, v))
}

// ValidFromNEQ applies the NEQ predicate on the "valid_from" field.
func ValidFromNEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldValidFrom, v))
}

// ValidFromIn applies the In predicate on the "valid_from" field.
func ValidFromIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldValidFrom, vs...))
}

// ValidFromNotIn applies the NotIn predicate on the "valid_from" field.
func ValidFromNotIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldValidFrom, vs...))
}

// ValidFromGT applies the GT predicate on the "valid_from" field.
func ValidFromGT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldValidFrom, v))
}

// ValidFromGTE applies the GTE predicate on the "valid_from" field.
func ValidFromGTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldValidFrom, v))
}

// ValidFromLT applies the LT predicate on the "valid_from" field.
func ValidFromLT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldValidFrom, v))
}

// ValidFromLTE applies the LTE predicate on the "valid_from" field.
func ValidFromLTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldValidFrom, v))
}

// ValidFromIsNil applies the IsNil predicate on the "valid_from" field.
func ValidFromIsNil() predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIsNull(FieldValidFrom))
}

// ValidFromNotNil applies the NotNil predicate on the "valid_from" field.
func ValidFromNotNil() predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotNull(FieldValidFrom))
}

// ValidToEQ applies the EQ predicate on the "valid_to" field.
func ValidToEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldValidTo, v))
}

// ValidToNEQ applies the NEQ predicate on the "valid_to" field.
func ValidToNEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldValidTo, v))
}

// ValidToIn applies the In predicate on the "valid_to" field.
func ValidToIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldValidTo, vs...))
}

// ValidToNotIn applies the NotIn predicate on the "valid_to" field.
func ValidToNotIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldValidTo, vs...))
}

// ValidToGT applies the GT predicate on the "valid_to" field.
func ValidToGT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldValidTo, v))
}

// ValidToGTE applies the GTE predicate on the "valid_to" field.
func ValidToGTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldValidTo, v))
}

// ValidToLT applies the LT predicate on the "valid_to" field.
func ValidToLT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldValidTo, v))
}

// ValidToLTE applies the LTE predicate on the "valid_to" field.
func ValidToLTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldValidTo, v))
}

// ValidToIsNil applies the IsNil predicate on the "valid_to" field.
func ValidToIsNil() predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIsNull(FieldValidTo))
}

// ValidToNotNil applies the NotNil predicate on the "valid_to" field.
func ValidToNotNil() predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotNull(FieldValidTo))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldContainsFold(FieldStatus, v))
}

// OpenedByEQ applies the EQ predicate on the "opened_by" field.
func OpenedByEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldOpenedBy, v))
}

// OpenedByNEQ applies the NEQ predicate on the "opened_by" field.
func OpenedByNEQ(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldOpenedBy, v))
}

// OpenedByIn applies the In predicate on the "opened_by" field.
func OpenedByIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldOpenedBy, vs...))
}

// OpenedByNotIn applies the NotIn predicate on the "opened_by" field.
func OpenedByNotIn(vs ...int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldOpenedBy, vs...))
}

// OpenedByGT applies the GT predicate on the "opened_by" field.
func OpenedByGT(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldOpenedBy, v))
}

// OpenedByGTE applies the GTE predicate on the "opened_by" field.
func OpenedByGTE(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldOpenedBy, v))
}

// OpenedByLT applies the LT predicate on the "opened_by" field.
func OpenedByLT(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldOpenedBy, v))
}

// OpenedByLTE applies the LTE predicate on the "opened_by" field.
func OpenedByLTE(v int64) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldOpenedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MemberCard {
	return predicate.MemberCard(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.MemberCard {
	return predicate.MemberCard(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.Member) predicate.MemberCard {
	return predicate.MemberCard(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItemBalances applies the HasEdge predicate on the "item_balances" edge.
func HasItemBalances() predicate.MemberCard {
	return predicate.MemberCard(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemBalancesTable, ItemBalancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemBalancesWith applies the HasEdge predicate on the "item_balances" edge with a given conditions (other predicates).
func HasItemBalancesWith(preds ...predicate.CardItemBalance) predicate.MemberCard {
	return predicate.MemberCard(func(s *sql.Selector) {
		step := newItemBalancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgers applies the HasEdge predicate on the "ledgers" edge.
func HasLedgers() predicate.MemberCard {
	return predicate.MemberCard(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedgersTable, LedgersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgersWith applies the HasEdge predicate on the "ledgers" edge with a given conditions (other predicates).
func HasLedgersWith(preds ...predicate.LedgerEntry) predicate.MemberCard {
	return predicate.MemberCard(func(s *sql.Selector) {
		step := newLedgersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemberCard) predicate.MemberCard {
	return predicate.MemberCard(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemberCard) predicate.MemberCard {
	return predicate.MemberCard(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemberCard) predicate.MemberCard {
	return predicate.MemberCard(sql.NotPredicates(p))
}
