// Code generated by ent, DO NOT EDIT.

package carditembalance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the carditembalance type in the database.
	Label = "card_item_balance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCardID holds the string denoting the card_id field in the database.
	FieldCardID = "card_id"
	// FieldProductItemID holds the string denoting the product_item_id field in the database.
	FieldProductItemID = "product_item_id"
	// FieldNameSnapshot holds the string denoting the name_snapshot field in the database.
	FieldNameSnapshot = "name_snapshot"
	// FieldRemainTimes holds the string denoting the remain_times field in the database.
	FieldRemainTimes = "remain_times"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCard holds the string denoting the card edge name in mutations.
	EdgeCard = "card"
	// Table holds the table name of the carditembalance in the database.
	Table = "card_item_balances"
	// CardTable is the table that holds the card relation/edge.
	CardTable = "card_item_balances"
	// CardInverseTable is the table name for the MemberCard entity.
	// It exists in this package in order to avoid circular dependency with the "membercard" package.
	CardInverseTable = "member_cards"
	// CardColumn is the table column denoting the card relation/edge.
	CardColumn = "card_id"
)

// Columns holds all SQL columns for carditembalance fields.
var Columns = []string{
	FieldID,
	FieldCardID,
	FieldProductItemID,
	FieldNameSnapshot,
	FieldRemainTimes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameSnapshotValidator is a validator for the "name_snapshot" field. It is called by the builders before save.
	NameSnapshotValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CardItemBalance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCardID orders the results by the card_id field.
func ByCardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardID, opts...).ToFunc()
}

// ByProductItemID orders the results by the product_item_id field.
func ByProductItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductItemID, opts...).ToFunc()
}

// ByNameSnapshot orders the results by the name_snapshot field.
func ByNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameSnapshot, opts...).ToFunc()
}

// ByRemainTimes orders the results by the remain_times field.
func ByRemainTimes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemainTimes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCardField orders the results by card field.
func ByCardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCardStep(), sql.OrderByField(field, opts...))
	}
}
func newCardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CardTable, CardColumn),
	)
}
