// Code generated by ent, DO NOT EDIT.

package carditembalance

import (
	"card_manager/api_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLTE(FieldID, id))
}

// CardID applies equality check predicate on the "card_id" field. It's identical to CardIDEQ.
func CardID(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldCardID, v))
}

// ProductItemID applies equality check predicate on the "product_item_id" field. It's identical to ProductItemIDEQ.
func ProductItemID(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldProductItemID, v))
}

// NameSnapshot applies equality check predicate on the "name_snapshot" field. It's identical to NameSnapshotEQ.
func NameSnapshot(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldNameSnapshot, v))
}

// RemainTimes applies equality check predicate on the "remain_times" field. It's identical to RemainTimesEQ.
func RemainTimes(v int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldRemainTimes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldUpdatedAt, v))
}

// CardIDEQ applies the EQ predicate on the "card_id" field.
func CardIDEQ(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldCardID, v))
}

// CardIDNEQ applies the NEQ predicate on the "card_id" field.
func CardIDNEQ(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNEQ(FieldCardID, v))
}

// CardIDIn applies the In predicate on the "card_id" field.
func CardIDIn(vs ...int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldIn(FieldCardID, vs...))
}

// CardIDNotIn applies the NotIn predicate on the "card_id" field.
func CardIDNotIn(vs ...int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNotIn(FieldCardID, vs...))
}

// ProductItemIDEQ applies the EQ predicate on the "product_item_id" field.
func ProductItemIDEQ(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldProductItemID, v))
}

// ProductItemIDNEQ applies the NEQ predicate on the "product_item_id" field.
func ProductItemIDNEQ(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNEQ(FieldProductItemID, v))
}

// ProductItemIDIn applies the In predicate on the "product_item_id" field.
func ProductItemIDIn(vs ...int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldIn(FieldProductItemID, vs...))
}

// ProductItemIDNotIn applies the NotIn predicate on the "product_item_id" field.
func ProductItemIDNotIn(vs ...int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNotIn(FieldProductItemID, vs...))
}

// ProductItemIDGT applies the GT predicate on the "product_item_id" field.
func ProductItemIDGT(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGT(FieldProductItemID, v))
}

// ProductItemIDGTE applies the GTE predicate on the "product_item_id" field.
func ProductItemIDGTE(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGTE(FieldProductItemID, v))
}

// ProductItemIDLT applies the LT predicate on the "product_item_id" field.
func ProductItemIDLT(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLT(FieldProductItemID, v))
}

// ProductItemIDLTE applies the LTE predicate on the "product_item_id" field.
func ProductItemIDLTE(v int64) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLTE(FieldProductItemID, v))
}

// NameSnapshotEQ applies the EQ predicate on the "name_snapshot" field.
func NameSnapshotEQ(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldNameSnapshot, v))
}

// NameSnapshotNEQ applies the NEQ predicate on the "name_snapshot" field.
func NameSnapshotNEQ(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNEQ(FieldNameSnapshot, v))
}

// NameSnapshotIn applies the In predicate on the "name_snapshot" field.
func NameSnapshotIn(vs ...string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldIn(FieldNameSnapshot, vs...))
}

// NameSnapshotNotIn applies the NotIn predicate on the "name_snapshot" field.
func NameSnapshotNotIn(vs ...string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNotIn(FieldNameSnapshot, vs...))
}

// NameSnapshotGT applies the GT predicate on the "name_snapshot" field.
func NameSnapshotGT(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGT(FieldNameSnapshot, v))
}

// NameSnapshotGTE applies the GTE predicate on the "name_snapshot" field.
func NameSnapshotGTE(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGTE(FieldNameSnapshot, v))
}

// NameSnapshotLT applies the LT predicate on the "name_snapshot" field.
func NameSnapshotLT(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLT(FieldNameSnapshot, v))
}

// NameSnapshotLTE applies the LTE predicate on the "name_snapshot" field.
func NameSnapshotLTE(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLTE(FieldNameSnapshot, v))
}

// NameSnapshotContains applies the Contains predicate on the "name_snapshot" field.
func NameSnapshotContains(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldContains(FieldNameSnapshot, v))
}

// NameSnapshotHasPrefix applies the HasPrefix predicate on the "name_snapshot" field.
func NameSnapshotHasPrefix(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldHasPrefix(FieldNameSnapshot, v))
}

// NameSnapshotHasSuffix applies the HasSuffix predicate on the "name_snapshot" field.
func NameSnapshotHasSuffix(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldHasSuffix(FieldNameSnapshot, v))
}

// NameSnapshotEqualFold applies the EqualFold predicate on the "name_snapshot" field.
func NameSnapshotEqualFold(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEqualFold(FieldNameSnapshot, v))
}

// NameSnapshotContainsFold applies the ContainsFold predicate on the "name_snapshot" field.
func NameSnapshotContainsFold(v string) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldContainsFold(FieldNameSnapshot, v))
}

// RemainTimesEQ applies the EQ predicate on the "remain_times" field.
func RemainTimesEQ(v int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldRemainTimes, v))
}

// RemainTimesNEQ applies the NEQ predicate on the "remain_times" field.
func RemainTimesNEQ(v int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNEQ(FieldRemainTimes, v))
}

// RemainTimesIn applies the In predicate on the "remain_times" field.
func RemainTimesIn(vs ...int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldIn(FieldRemainTimes, vs...))
}

// RemainTimesNotIn applies the NotIn predicate on the "remain_times" field.
func RemainTimesNotIn(vs ...int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNotIn(FieldRemainTimes, vs...))
}

// RemainTimesGT applies the GT predicate on the "remain_times" field.
func RemainTimesGT(v int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGT(FieldRemainTimes, v))
}

// RemainTimesGTE applies the GTE predicate on the "remain_times" field.
func RemainTimesGTE(v int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGTE(FieldRemainTimes, v))
}

// RemainTimesLT applies the LT predicate on the "remain_times" field.
func RemainTimesLT(v int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLT(FieldRemainTimes, v))
}

// RemainTimesLTE applies the LTE predicate on the "remain_times" field.
func RemainTimesLTE(v int) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLTE(FieldRemainTimes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCard applies the HasEdge predicate on the "card" edge.
func HasCard() predicate.CardItemBalance {
	return predicate.CardItemBalance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CardTable, CardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCardWith applies the HasEdge predicate on the "card" edge with a given conditions (other predicates).
func HasCardWith(preds ...predicate.MemberCard) predicate.CardItemBalance {
	return predicate.CardItemBalance(func(s *sql.Selector) {
		step := newCardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CardItemBalance) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CardItemBalance) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CardItemBalance) predicate.CardItemBalance {
	return predicate.CardItemBalance(sql.NotPredicates(p))
}
