// Code generated by ent, DO NOT EDIT.

package ledgerentry

import (
	"card_manager/api_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldID, id))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldStoreID, v))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldMemberID, v))
}

// CardID applies equality check predicate on the "card_id" field. It's identical to CardIDEQ.
func CardID(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldCardID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldType, v))
}

// CardType applies equality check predicate on the "card_type" field. It's identical to CardTypeEQ.
func CardType(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldCardType, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldAmount, v))
}

// Times applies equality check predicate on the "times" field. It's identical to TimesEQ.
func Times(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldTimes, v))
}

// ItemName applies equality check predicate on the "item_name" field. It's identical to ItemNameEQ.
func ItemName(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldItemName, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldBalanceAfter, v))
}

// TimesAfter applies equality check predicate on the "times_after" field. It's identical to TimesAfterEQ.
func TimesAfter(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldTimesAfter, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldRemark, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldOperatorID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldStoreID, vs...))
}

// StoreIDGT applies the GT predicate on the "store_id" field.
func StoreIDGT(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldStoreID, v))
}

// StoreIDGTE applies the GTE predicate on the "store_id" field.
func StoreIDGTE(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldStoreID, v))
}

// StoreIDLT applies the LT predicate on the "store_id" field.
func StoreIDLT(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldStoreID, v))
}

// StoreIDLTE applies the LTE predicate on the "store_id" field.
func StoreIDLTE(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldStoreID, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldMemberID, vs...))
}

// CardIDEQ applies the EQ predicate on the "card_id" field.
func CardIDEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldCardID, v))
}

// CardIDNEQ applies the NEQ predicate on the "card_id" field.
func CardIDNEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldCardID, v))
}

// CardIDIn applies the In predicate on the "card_id" field.
func CardIDIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldCardID, vs...))
}

// CardIDNotIn applies the NotIn predicate on the "card_id" field.
func CardIDNotIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldCardID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContainsFold(FieldType, v))
}

// CardTypeEQ applies the EQ predicate on the "card_type" field.
func CardTypeEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldCardType, v))
}

// CardTypeNEQ applies the NEQ predicate on the "card_type" field.
func CardTypeNEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldCardType, v))
}

// CardTypeIn applies the In predicate on the "card_type" field.
func CardTypeIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldCardType, vs...))
}

// CardTypeNotIn applies the NotIn predicate on the "card_type" field.
func CardTypeNotIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldCardType, vs...))
}

// CardTypeGT applies the GT predicate on the "card_type" field.
func CardTypeGT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldCardType, v))
}

// CardTypeGTE applies the GTE predicate on the "card_type" field.
func CardTypeGTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldCardType, v))
}

// CardTypeLT applies the LT predicate on the "card_type" field.
func CardTypeLT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldCardType, v))
}

// CardTypeLTE applies the LTE predicate on the "card_type" field.
func CardTypeLTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldCardType, v))
}

// CardTypeContains applies the Contains predicate on the "card_type" field.
func CardTypeContains(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContains(FieldCardType, v))
}

// CardTypeHasPrefix applies the HasPrefix predicate on the "card_type" field.
func CardTypeHasPrefix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasPrefix(FieldCardType, v))
}

// CardTypeHasSuffix applies the HasSuffix predicate on the "card_type" field.
func CardTypeHasSuffix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasSuffix(FieldCardType, v))
}

// CardTypeEqualFold applies the EqualFold predicate on the "card_type" field.
func CardTypeEqualFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEqualFold(FieldCardType, v))
}

// CardTypeContainsFold applies the ContainsFold predicate on the "card_type" field.
func CardTypeContainsFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContainsFold(FieldCardType, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldAmount, v))
}

// AmountIsNil applies the IsNil predicate on the "amount" field.
func AmountIsNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIsNull(FieldAmount))
}

// AmountNotNil applies the NotNil predicate on the "amount" field.
func AmountNotNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotNull(FieldAmount))
}

// TimesEQ applies the EQ predicate on the "times" field.
func TimesEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldTimes, v))
}

// TimesNEQ applies the NEQ predicate on the "times" field.
func TimesNEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldTimes, v))
}

// TimesIn applies the In predicate on the "times" field.
func TimesIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldTimes, vs...))
}

// TimesNotIn applies the NotIn predicate on the "times" field.
func TimesNotIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldTimes, vs...))
}

// TimesGT applies the GT predicate on the "times" field.
func TimesGT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldTimes, v))
}

// TimesGTE applies the GTE predicate on the "times" field.
func TimesGTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldTimes, v))
}

// TimesLT applies the LT predicate on the "times" field.
func TimesLT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldTimes, v))
}

// TimesLTE applies the LTE predicate on the "times" field.
func TimesLTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldTimes, v))
}

// TimesIsNil applies the IsNil predicate on the "times" field.
func TimesIsNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIsNull(FieldTimes))
}

// TimesNotNil applies the NotNil predicate on the "times" field.
func TimesNotNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotNull(FieldTimes))
}

// ItemNameEQ applies the EQ predicate on the "item_name" field.
func ItemNameEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldItemName, v))
}

// ItemNameNEQ applies the NEQ predicate on the "item_name" field.
func ItemNameNEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldItemName, v))
}

// ItemNameIn applies the In predicate on the "item_name" field.
func ItemNameIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldItemName, vs...))
}

// ItemNameNotIn applies the NotIn predicate on the "item_name" field.
func ItemNameNotIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldItemName, vs...))
}

// ItemNameGT applies the GT predicate on the "item_name" field.
func ItemNameGT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldItemName, v))
}

// ItemNameGTE applies the GTE predicate on the "item_name" field.
func ItemNameGTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldItemName, v))
}

// ItemNameLT applies the LT predicate on the "item_name" field.
func ItemNameLT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldItemName, v))
}

// ItemNameLTE applies the LTE predicate on the "item_name" field.
func ItemNameLTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldItemName, v))
}

// ItemNameContains applies the Contains predicate on the "item_name" field.
func ItemNameContains(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContains(FieldItemName, v))
}

// ItemNameHasPrefix applies the HasPrefix predicate on the "item_name" field.
func ItemNameHasPrefix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasPrefix(FieldItemName, v))
}

// ItemNameHasSuffix applies the HasSuffix predicate on the "item_name" field.
func ItemNameHasSuffix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasSuffix(FieldItemName, v))
}

// ItemNameIsNil applies the IsNil predicate on the "item_name" field.
func ItemNameIsNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIsNull(FieldItemName))
}

// ItemNameNotNil applies the NotNil predicate on the "item_name" field.
func ItemNameNotNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotNull(FieldItemName))
}

// ItemNameEqualFold applies the EqualFold predicate on the "item_name" field.
func ItemNameEqualFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEqualFold(FieldItemName, v))
}

// ItemNameContainsFold applies the ContainsFold predicate on the "item_name" field.
func ItemNameContainsFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContainsFold(FieldItemName, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldBalanceAfter, v))
}

// BalanceAfterIsNil applies the IsNil predicate on the "balance_after" field.
func BalanceAfterIsNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIsNull(FieldBalanceAfter))
}

// BalanceAfterNotNil applies the NotNil predicate on the "balance_after" field.
func BalanceAfterNotNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotNull(FieldBalanceAfter))
}

// TimesAfterEQ applies the EQ predicate on the "times_after" field.
func TimesAfterEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldTimesAfter, v))
}

// TimesAfterNEQ applies the NEQ predicate on the "times_after" field.
func TimesAfterNEQ(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldTimesAfter, v))
}

// TimesAfterIn applies the In predicate on the "times_after" field.
func TimesAfterIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldTimesAfter, vs...))
}

// TimesAfterNotIn applies the NotIn predicate on the "times_after" field.
func TimesAfterNotIn(vs ...int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldTimesAfter, vs...))
}

// TimesAfterGT applies the GT predicate on the "times_after" field.
func TimesAfterGT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldTimesAfter, v))
}

// TimesAfterGTE applies the GTE predicate on the "times_after" field.
func TimesAfterGTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldTimesAfter, v))
}

// TimesAfterLT applies the LT predicate on the "times_after" field.
func TimesAfterLT(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldTimesAfter, v))
}

// TimesAfterLTE applies the LTE predicate on the "times_after" field.
func TimesAfterLTE(v int) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldTimesAfter, v))
}

// TimesAfterIsNil applies the IsNil predicate on the "times_after" field.
func TimesAfterIsNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIsNull(FieldTimesAfter))
}

// TimesAfterNotNil applies the NotNil predicate on the "times_after" field.
func TimesAfterNotNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotNull(FieldTimesAfter))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldContainsFold(FieldRemark, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int64) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldOperatorID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.LedgerEntry {
	return predicate.LedgerEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.Member) predicate.LedgerEntry {
	return predicate.LedgerEntry(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCard applies the HasEdge predicate on the "card" edge.
func HasCard() predicate.LedgerEntry {
	return predicate.LedgerEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CardTable, CardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCardWith applies the HasEdge predicate on the "card" edge with a given conditions (other predicates).
func HasCardWith(preds ...predicate.MemberCard) predicate.LedgerEntry {
	return predicate.LedgerEntry(func(s *sql.Selector) {
		step := newCardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.LedgerEntry {
	return predicate.LedgerEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.LedgerEntryItem) predicate.LedgerEntry {
	return predicate.LedgerEntry(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LedgerEntry) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LedgerEntry) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LedgerEntry) predicate.LedgerEntry {
	return predicate.LedgerEntry(sql.NotPredicates(p))
}
