// Code generated by ent, DO NOT EDIT.

package oauthidentity

import (
	"card_manager/api_service/ent/predicate"
	"context"
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Mutation represents an operation that mutates the OAuthIdentity nodes in the graph.
type Mutation struct {
	op            ent.Op
	typ           string
	provider      *string
	provider_uid  *string
	union_id      *string
	user_id       *int64
	adduser_id    *int64
	nickname      *string
	avatar_url    *string
	extra         *map[string]interface{}
	authorized_at *time.Time
	bound_at      *time.Time
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	predicates    []predicate.OAuthIdentity
}

// NewMutation creates a new Mutation for the OAuthIdentity entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "OAuthIdentity",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.OAuthIdentity {
	return m.predicates
}

// SetProvider sets the "provider" field.
func (m *Mutation) SetProvider(s string) {
	m.provider = &s
}

// Provider returns the value of the "provider" field in the mutation.
func (m *Mutation) Provider() (r string, exists bool) {
	v := m.provider
	if v == nil {
		return
	}
	return *v, true
}

// ResetProvider resets all changes to the "provider" field.
func (m *Mutation) ResetProvider() {
	m.provider = nil
}

// SetProviderUID sets the "provider_uid" field.
func (m *Mutation) SetProviderUID(s string) {
	m.provider_uid = &s
}

// ProviderUID returns the value of the "provider_uid" field in the mutation.
func (m *Mutation) ProviderUID() (r string, exists bool) {
	v := m.provider_uid
	if v == nil {
		return
	}
	return *v, true
}

// ResetProviderUID resets all changes to the "provider_uid" field.
func (m *Mutation) ResetProviderUID() {
	m.provider_uid = nil
}

// SetUnionID sets the "union_id" field.
func (m *Mutation) SetUnionID(s string) {
	m.union_id = &s
}

// UnionID returns the value of the "union_id" field in the mutation.
func (m *Mutation) UnionID() (r string, exists bool) {
	v := m.union_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearUnionID clears the value of the "union_id" field.
func (m *Mutation) ClearUnionID() {
	m.union_id = nil
	m.clearedFields[FieldUnionID] = struct{}{}
}

// UnionIDCleared returns if the "union_id" field was cleared in this mutation.
func (m *Mutation) UnionIDCleared() bool {
	_, ok := m.clearedFields[FieldUnionID]
	return ok
}

// ResetUnionID resets all changes to the "union_id" field.
func (m *Mutation) ResetUnionID() {
	m.union_id = nil
	delete(m.clearedFields, FieldUnionID)
}

// SetUserID sets the "user_id" field.
func (m *Mutation) SetUserID(i int64) {
	m.user_id = &i
	m.adduser_id = nil
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *Mutation) UserID() (r int64, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// AddUserID adds i to the "user_id" field.
func (m *Mutation) AddUserID(i int64) {
	if m.adduser_id != nil {
		*m.adduser_id += i
	} else {
		m.adduser_id = &i
	}
}

// AddedUserID returns the value that was added to the "user_id" field in this mutation.
func (m *Mutation) AddedUserID() (r int64, exists bool) {
	v := m.adduser_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserID resets all changes to the "user_id" field.
func (m *Mutation) ResetUserID() {
	m.user_id = nil
	m.adduser_id = nil
}

// SetNickname sets the "nickname" field.
func (m *Mutation) SetNickname(s string) {
	m.nickname = &s
}

// Nickname returns the value of the "nickname" field in the mutation.
func (m *Mutation) Nickname() (r string, exists bool) {
	v := m.nickname
	if v == nil {
		return
	}
	return *v, true
}

// ClearNickname clears the value of the "nickname" field.
func (m *Mutation) ClearNickname() {
	m.nickname = nil
	m.clearedFields[FieldNickname] = struct{}{}
}

// NicknameCleared returns if the "nickname" field was cleared in this mutation.
func (m *Mutation) NicknameCleared() bool {
	_, ok := m.clearedFields[FieldNickname]
	return ok
}

// ResetNickname resets all changes to the "nickname" field.
func (m *Mutation) ResetNickname() {
	m.nickname = nil
	delete(m.clearedFields, FieldNickname)
}

// SetAvatarURL sets the "avatar_url" field.
func (m *Mutation) SetAvatarURL(s string) {
	m.avatar_url = &s
}

// AvatarURL returns the value of the "avatar_url" field in the mutation.
func (m *Mutation) AvatarURL() (r string, exists bool) {
	v := m.avatar_url
	if v == nil {
		return
	}
	return *v, true
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (m *Mutation) ClearAvatarURL() {
	m.avatar_url = nil
	m.clearedFields[FieldAvatarURL] = struct{}{}
}

// AvatarURLCleared returns if the "avatar_url" field was cleared in this mutation.
func (m *Mutation) AvatarURLCleared() bool {
	_, ok := m.clearedFields[FieldAvatarURL]
	return ok
}

// ResetAvatarURL resets all changes to the "avatar_url" field.
func (m *Mutation) ResetAvatarURL() {
	m.avatar_url = nil
	delete(m.clearedFields, FieldAvatarURL)
}

// SetExtra sets the "extra" field.
func (m *Mutation) SetExtra(value map[string]interface{}) {
	m.extra = &value
}

// Extra returns the value of the "extra" field in the mutation.
func (m *Mutation) Extra() (r map[string]interface{}, exists bool) {
	v := m.extra
	if v == nil {
		return
	}
	return *v, true
}

// ClearExtra clears the value of the "extra" field.
func (m *Mutation) ClearExtra() {
	m.extra = nil
	m.clearedFields[FieldExtra] = struct{}{}
}

// ExtraCleared returns if the "extra" field was cleared in this mutation.
func (m *Mutation) ExtraCleared() bool {
	_, ok := m.clearedFields[FieldExtra]
	return ok
}

// ResetExtra resets all changes to the "extra" field.
func (m *Mutation) ResetExtra() {
	m.extra = nil
	delete(m.clearedFields, FieldExtra)
}

// SetAuthorizedAt sets the "authorized_at" field.
func (m *Mutation) SetAuthorizedAt(t time.Time) {
	m.authorized_at = &t
}

// AuthorizedAt returns the value of the "authorized_at" field in the mutation.
func (m *Mutation) AuthorizedAt() (r time.Time, exists bool) {
	v := m.authorized_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetAuthorizedAt resets all changes to the "authorized_at" field.
func (m *Mutation) ResetAuthorizedAt() {
	m.authorized_at = nil
}

// SetBoundAt sets the "bound_at" field.
func (m *Mutation) SetBoundAt(t time.Time) {
	m.bound_at = &t
}

// BoundAt returns the value of the "bound_at" field in the mutation.
func (m *Mutation) BoundAt() (r time.Time, exists bool) {
	v := m.bound_at
	if v == nil {
		return
	}
	return *v, true
}

// ClearBoundAt clears the value of the "bound_at" field.
func (m *Mutation) ClearBoundAt() {
	m.bound_at = nil
	m.clearedFields[FieldBoundAt] = struct{}{}
}

// BoundAtCleared returns if the "bound_at" field was cleared in this mutation.
func (m *Mutation) BoundAtCleared() bool {
	_, ok := m.clearedFields[FieldBoundAt]
	return ok
}

// ResetBoundAt resets all changes to the "bound_at" field.
func (m *Mutation) ResetBoundAt() {
	m.bound_at = nil
	delete(m.clearedFields, FieldBoundAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *Mutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *Mutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *Mutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *Mutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *Mutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *Mutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.OAuthIdentity) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.OAuthIdentity, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (OAuthIdentity).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.provider != nil {
		fields = append(fields, FieldProvider)
	}
	if m.provider_uid != nil {
		fields = append(fields, FieldProviderUID)
	}
	if m.union_id != nil {
		fields = append(fields, FieldUnionID)
	}
	if m.user_id != nil {
		fields = append(fields, FieldUserID)
	}
	if m.nickname != nil {
		fields = append(fields, FieldNickname)
	}
	if m.avatar_url != nil {
		fields = append(fields, FieldAvatarURL)
	}
	if m.extra != nil {
		fields = append(fields, FieldExtra)
	}
	if m.authorized_at != nil {
		fields = append(fields, FieldAuthorizedAt)
	}
	if m.bound_at != nil {
		fields = append(fields, FieldBoundAt)
	}
	if m.created_at != nil {
		fields = append(fields, FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldProvider:
		return m.Provider()
	case FieldProviderUID:
		return m.ProviderUID()
	case FieldUnionID:
		return m.UnionID()
	case FieldUserID:
		return m.UserID()
	case FieldNickname:
		return m.Nickname()
	case FieldAvatarURL:
		return m.AvatarURL()
	case FieldExtra:
		return m.Extra()
	case FieldAuthorizedAt:
		return m.AuthorizedAt()
	case FieldBoundAt:
		return m.BoundAt()
	case FieldCreatedAt:
		return m.CreatedAt()
	case FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown OAuthIdentity field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldProvider:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProvider(v)
		return nil
	case FieldProviderUID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderUID(v)
		return nil
	case FieldUnionID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUnionID(v)
		return nil
	case FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case FieldNickname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNickname(v)
		return nil
	case FieldAvatarURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAvatarURL(v)
		return nil
	case FieldExtra:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExtra(v)
		return nil
	case FieldAuthorizedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthorizedAt(v)
		return nil
	case FieldBoundAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBoundAt(v)
		return nil
	case FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown OAuthIdentity field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	var fields []string
	if m.adduser_id != nil {
		fields = append(fields, FieldUserID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case FieldUserID:
		return m.AddedUserID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	case FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserID(v)
		return nil
	}
	return fmt.Errorf("unknown OAuthIdentity numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldUnionID) {
		fields = append(fields, FieldUnionID)
	}
	if m.FieldCleared(FieldNickname) {
		fields = append(fields, FieldNickname)
	}
	if m.FieldCleared(FieldAvatarURL) {
		fields = append(fields, FieldAvatarURL)
	}
	if m.FieldCleared(FieldExtra) {
		fields = append(fields, FieldExtra)
	}
	if m.FieldCleared(FieldBoundAt) {
		fields = append(fields, FieldBoundAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldUnionID:
		m.ClearUnionID()
		return nil
	case FieldNickname:
		m.ClearNickname()
		return nil
	case FieldAvatarURL:
		m.ClearAvatarURL()
		return nil
	case FieldExtra:
		m.ClearExtra()
		return nil
	case FieldBoundAt:
		m.ClearBoundAt()
		return nil
	}
	return fmt.Errorf("unknown OAuthIdentity nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldProvider:
		m.ResetProvider()
		return nil
	case FieldProviderUID:
		m.ResetProviderUID()
		return nil
	case FieldUnionID:
		m.ResetUnionID()
		return nil
	case FieldUserID:
		m.ResetUserID()
		return nil
	case FieldNickname:
		m.ResetNickname()
		return nil
	case FieldAvatarURL:
		m.ResetAvatarURL()
		return nil
	case FieldExtra:
		m.ResetExtra()
		return nil
	case FieldAuthorizedAt:
		m.ResetAuthorizedAt()
		return nil
	case FieldBoundAt:
		m.ResetBoundAt()
		return nil
	case FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown OAuthIdentity field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown OAuthIdentity unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown OAuthIdentity edge %s", name)
}
