// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/cardproduct"
	"card_manager/api_service/ent/cardproductitem"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CardProductCreate is the builder for creating a CardProduct entity.
type CardProductCreate struct {
	config
	mutation *CardProductMutation
	hooks    []Hook
}

// SetStoreID sets the "store_id" field.
func (_c *CardProductCreate) SetStoreID(v int64) *CardProductCreate {
	_c.mutation.SetStoreID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *CardProductCreate) SetType(v string) *CardProductCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CardProductCreate) SetName(v string) *CardProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *CardProductCreate) SetPrice(v int) *CardProductCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *CardProductCreate) SetNillablePrice(v *int) *CardProductCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetTimes sets the "times" field.
func (_c *CardProductCreate) SetTimes(v int) *CardProductCreate {
	_c.mutation.SetTimes(v)
	return _c
}

// SetNillableTimes sets the "times" field if the given value is not nil.
func (_c *CardProductCreate) SetNillableTimes(v *int) *CardProductCreate {
	if v != nil {
		_c.SetTimes(*v)
	}
	return _c
}

// SetValidMonths sets the "valid_months" field.
func (_c *CardProductCreate) SetValidMonths(v int) *CardProductCreate {
	_c.mutation.SetValidMonths(v)
	return _c
}

// SetNillableValidMonths sets the "valid_months" field if the given value is not nil.
func (_c *CardProductCreate) SetNillableValidMonths(v *int) *CardProductCreate {
	if v != nil {
		_c.SetValidMonths(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CardProductCreate) SetStatus(v int8) *CardProductCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CardProductCreate) SetNillableStatus(v *int8) *CardProductCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CardProductCreate) SetCreatedAt(v time.Time) *CardProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CardProductCreate) SetNillableCreatedAt(v *time.Time) *CardProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CardProductCreate) SetUpdatedAt(v time.Time) *CardProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CardProductCreate) SetNillableUpdatedAt(v *time.Time) *CardProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CardProductCreate) SetID(v int64) *CardProductCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddItemIDs adds the "items" edge to the CardProductItem entity by IDs.
func (_c *CardProductCreate) AddItemIDs(ids ...int64) *CardProductCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the CardProductItem entity.
func (_c *CardProductCreate) AddItems(v ...*CardProductItem) *CardProductCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the CardProductMutation object of the builder.
func (_c *CardProductCreate) Mutation() *CardProductMutation {
	return _c.mutation
}

// Save creates the CardProduct in the database.
func (_c *CardProductCreate) Save(ctx context.Context) (*CardProduct, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CardProductCreate) SaveX(ctx context.Context) *CardProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CardProductCreate) defaults() {
	if _, ok := _c.mutation.Price(); !ok {
		v := cardproduct.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := cardproduct.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cardproduct.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cardproduct.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CardProductCreate) check() error {
	if _, ok := _c.mutation.StoreID(); !ok {
		return &ValidationError{Name: "store_id", err: errors.New(`ent: missing required field "CardProduct.store_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "CardProduct.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := cardproduct.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CardProduct.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CardProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := cardproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CardProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "CardProduct.price"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CardProduct.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CardProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CardProduct.updated_at"`)}
	}
	return nil
}

func (_c *CardProductCreate) sqlSave(ctx context.Context) (*CardProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CardProductCreate) createSpec() (*CardProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &CardProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cardproduct.Table, sqlgraph.NewFieldSpec(cardproduct.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StoreID(); ok {
		_spec.SetField(cardproduct.FieldStoreID, field.TypeInt64, value)
		_node.StoreID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(cardproduct.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(cardproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(cardproduct.FieldPrice, field.TypeInt, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Times(); ok {
		_spec.SetField(cardproduct.FieldTimes, field.TypeInt, value)
		_node.Times = &value
	}
	if value, ok := _c.mutation.ValidMonths(); ok {
		_spec.SetField(cardproduct.FieldValidMonths, field.TypeInt, value)
		_node.ValidMonths = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cardproduct.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cardproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cardproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cardproduct.ItemsTable,
			Columns: []string{cardproduct.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cardproductitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CardProductCreateBulk is the builder for creating many CardProduct entities in bulk.
type CardProductCreateBulk struct {
	config
	err      error
	builders []*CardProductCreate
}

// Save creates the CardProduct entities in the database.
func (_c *CardProductCreateBulk) Save(ctx context.Context) ([]*CardProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CardProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CardProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CardProductCreateBulk) SaveX(ctx context.Context) []*CardProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
