// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/ledgerentry"
	"card_manager/api_service/ent/ledgerentryitem"
	"card_manager/api_service/ent/member"
	"card_manager/api_service/ent/membercard"
	"card_manager/api_service/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerEntryUpdate is the builder for updating LedgerEntry entities.
type LedgerEntryUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerEntryMutation
}

// Where appends a list predicates to the LedgerEntryUpdate builder.
func (_u *LedgerEntryUpdate) Where(ps ...predicate.LedgerEntry) *LedgerEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *LedgerEntryUpdate) SetStoreID(v int64) *LedgerEntryUpdate {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableStoreID(v *int64) *LedgerEntryUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *LedgerEntryUpdate) AddStoreID(v int64) *LedgerEntryUpdate {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *LedgerEntryUpdate) SetMemberID(v int64) *LedgerEntryUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableMemberID(v *int64) *LedgerEntryUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetCardID sets the "card_id" field.
func (_u *LedgerEntryUpdate) SetCardID(v int64) *LedgerEntryUpdate {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableCardID(v *int64) *LedgerEntryUpdate {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *LedgerEntryUpdate) SetType(v string) *LedgerEntryUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableType(v *string) *LedgerEntryUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCardType sets the "card_type" field.
func (_u *LedgerEntryUpdate) SetCardType(v string) *LedgerEntryUpdate {
	_u.mutation.SetCardType(v)
	return _u
}

// SetNillableCardType sets the "card_type" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableCardType(v *string) *LedgerEntryUpdate {
	if v != nil {
		_u.SetCardType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *LedgerEntryUpdate) SetAmount(v int) *LedgerEntryUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableAmount(v *int) *LedgerEntryUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *LedgerEntryUpdate) AddAmount(v int) *LedgerEntryUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// ClearAmount clears the value of the "amount" field.
func (_u *LedgerEntryUpdate) ClearAmount() *LedgerEntryUpdate {
	_u.mutation.ClearAmount()
	return _u
}

// SetTimes sets the "times" field.
func (_u *LedgerEntryUpdate) SetTimes(v int) *LedgerEntryUpdate {
	_u.mutation.ResetTimes()
	_u.mutation.SetTimes(v)
	return _u
}

// SetNillableTimes sets the "times" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableTimes(v *int) *LedgerEntryUpdate {
	if v != nil {
		_u.SetTimes(*v)
	}
	return _u
}

// AddTimes adds value to the "times" field.
func (_u *LedgerEntryUpdate) AddTimes(v int) *LedgerEntryUpdate {
	_u.mutation.AddTimes(v)
	return _u
}

// ClearTimes clears the value of the "times" field.
func (_u *LedgerEntryUpdate) ClearTimes() *LedgerEntryUpdate {
	_u.mutation.ClearTimes()
	return _u
}

// SetItemName sets the "item_name" field.
func (_u *LedgerEntryUpdate) SetItemName(v string) *LedgerEntryUpdate {
	_u.mutation.SetItemName(v)
	return _u
}

// SetNillableItemName sets the "item_name" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableItemName(v *string) *LedgerEntryUpdate {
	if v != nil {
		_u.SetItemName(*v)
	}
	return _u
}

// ClearItemName clears the value of the "item_name" field.
func (_u *LedgerEntryUpdate) ClearItemName() *LedgerEntryUpdate {
	_u.mutation.ClearItemName()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *LedgerEntryUpdate) SetBalanceAfter(v int) *LedgerEntryUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableBalanceAfter(v *int) *LedgerEntryUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *LedgerEntryUpdate) AddBalanceAfter(v int) *LedgerEntryUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *LedgerEntryUpdate) ClearBalanceAfter() *LedgerEntryUpdate {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetTimesAfter sets the "times_after" field.
func (_u *LedgerEntryUpdate) SetTimesAfter(v int) *LedgerEntryUpdate {
	_u.mutation.ResetTimesAfter()
	_u.mutation.SetTimesAfter(v)
	return _u
}

// SetNillableTimesAfter sets the "times_after" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableTimesAfter(v *int) *LedgerEntryUpdate {
	if v != nil {
		_u.SetTimesAfter(*v)
	}
	return _u
}

// AddTimesAfter adds value to the "times_after" field.
func (_u *LedgerEntryUpdate) AddTimesAfter(v int) *LedgerEntryUpdate {
	_u.mutation.AddTimesAfter(v)
	return _u
}

// ClearTimesAfter clears the value of the "times_after" field.
func (_u *LedgerEntryUpdate) ClearTimesAfter() *LedgerEntryUpdate {
	_u.mutation.ClearTimesAfter()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *LedgerEntryUpdate) SetRemark(v string) *LedgerEntryUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableRemark(v *string) *LedgerEntryUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *LedgerEntryUpdate) ClearRemark() *LedgerEntryUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *LedgerEntryUpdate) SetOperatorID(v int64) *LedgerEntryUpdate {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *LedgerEntryUpdate) SetNillableOperatorID(v *int64) *LedgerEntryUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *LedgerEntryUpdate) AddOperatorID(v int64) *LedgerEntryUpdate {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *LedgerEntryUpdate) SetMember(v *Member) *LedgerEntryUpdate {
	return _u.SetMemberID(v.ID)
}

// SetCard sets the "card" edge to the MemberCard entity.
func (_u *LedgerEntryUpdate) SetCard(v *MemberCard) *LedgerEntryUpdate {
	return _u.SetCardID(v.ID)
}

// AddItemIDs adds the "items" edge to the LedgerEntryItem entity by IDs.
func (_u *LedgerEntryUpdate) AddItemIDs(ids ...int64) *LedgerEntryUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the LedgerEntryItem entity.
func (_u *LedgerEntryUpdate) AddItems(v ...*LedgerEntryItem) *LedgerEntryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the LedgerEntryMutation object of the builder.
func (_u *LedgerEntryUpdate) Mutation() *LedgerEntryMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *LedgerEntryUpdate) ClearMember() *LedgerEntryUpdate {
	_u.mutation.ClearMember()
	return _u
}

// ClearCard clears the "card" edge to the MemberCard entity.
func (_u *LedgerEntryUpdate) ClearCard() *LedgerEntryUpdate {
	_u.mutation.ClearCard()
	return _u
}

// ClearItems clears all "items" edges to the LedgerEntryItem entity.
func (_u *LedgerEntryUpdate) ClearItems() *LedgerEntryUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to LedgerEntryItem entities by IDs.
func (_u *LedgerEntryUpdate) RemoveItemIDs(ids ...int64) *LedgerEntryUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to LedgerEntryItem entities.
func (_u *LedgerEntryUpdate) RemoveItems(v ...*LedgerEntryItem) *LedgerEntryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LedgerEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LedgerEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerEntryUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := ledgerentry.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CardType(); ok {
		if err := ledgerentry.CardTypeValidator(v); err != nil {
			return &ValidationError{Name: "card_type", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.card_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemName(); ok {
		if err := ledgerentry.ItemNameValidator(v); err != nil {
			return &ValidationError{Name: "item_name", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.item_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := ledgerentry.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.remark": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerEntry.member"`)
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerEntry.card"`)
	}
	return nil
}

func (_u *LedgerEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgerentry.Table, ledgerentry.Columns, sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(ledgerentry.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(ledgerentry.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ledgerentry.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CardType(); ok {
		_spec.SetField(ledgerentry.FieldCardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(ledgerentry.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(ledgerentry.FieldAmount, field.TypeInt, value)
	}
	if _u.mutation.AmountCleared() {
		_spec.ClearField(ledgerentry.FieldAmount, field.TypeInt)
	}
	if value, ok := _u.mutation.Times(); ok {
		_spec.SetField(ledgerentry.FieldTimes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimes(); ok {
		_spec.AddField(ledgerentry.FieldTimes, field.TypeInt, value)
	}
	if _u.mutation.TimesCleared() {
		_spec.ClearField(ledgerentry.FieldTimes, field.TypeInt)
	}
	if value, ok := _u.mutation.ItemName(); ok {
		_spec.SetField(ledgerentry.FieldItemName, field.TypeString, value)
	}
	if _u.mutation.ItemNameCleared() {
		_spec.ClearField(ledgerentry.FieldItemName, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(ledgerentry.FieldBalanceAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(ledgerentry.FieldBalanceAfter, field.TypeInt, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(ledgerentry.FieldBalanceAfter, field.TypeInt)
	}
	if value, ok := _u.mutation.TimesAfter(); ok {
		_spec.SetField(ledgerentry.FieldTimesAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimesAfter(); ok {
		_spec.AddField(ledgerentry.FieldTimesAfter, field.TypeInt, value)
	}
	if _u.mutation.TimesAfterCleared() {
		_spec.ClearField(ledgerentry.FieldTimesAfter, field.TypeInt)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(ledgerentry.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(ledgerentry.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(ledgerentry.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(ledgerentry.FieldOperatorID, field.TypeInt64, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.MemberTable,
			Columns: []string{ledgerentry.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.MemberTable,
			Columns: []string{ledgerentry.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.CardTable,
			Columns: []string{ledgerentry.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.CardTable,
			Columns: []string{ledgerentry.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerentry.ItemsTable,
			Columns: []string{ledgerentry.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentryitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerentry.ItemsTable,
			Columns: []string{ledgerentry.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerentry.ItemsTable,
			Columns: []string{ledgerentry.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgerentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LedgerEntryUpdateOne is the builder for updating a single LedgerEntry entity.
type LedgerEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerEntryMutation
}

// SetStoreID sets the "store_id" field.
func (_u *LedgerEntryUpdateOne) SetStoreID(v int64) *LedgerEntryUpdateOne {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableStoreID(v *int64) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *LedgerEntryUpdateOne) AddStoreID(v int64) *LedgerEntryUpdateOne {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *LedgerEntryUpdateOne) SetMemberID(v int64) *LedgerEntryUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableMemberID(v *int64) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetCardID sets the "card_id" field.
func (_u *LedgerEntryUpdateOne) SetCardID(v int64) *LedgerEntryUpdateOne {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableCardID(v *int64) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *LedgerEntryUpdateOne) SetType(v string) *LedgerEntryUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableType(v *string) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCardType sets the "card_type" field.
func (_u *LedgerEntryUpdateOne) SetCardType(v string) *LedgerEntryUpdateOne {
	_u.mutation.SetCardType(v)
	return _u
}

// SetNillableCardType sets the "card_type" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableCardType(v *string) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetCardType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *LedgerEntryUpdateOne) SetAmount(v int) *LedgerEntryUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableAmount(v *int) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *LedgerEntryUpdateOne) AddAmount(v int) *LedgerEntryUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// ClearAmount clears the value of the "amount" field.
func (_u *LedgerEntryUpdateOne) ClearAmount() *LedgerEntryUpdateOne {
	_u.mutation.ClearAmount()
	return _u
}

// SetTimes sets the "times" field.
func (_u *LedgerEntryUpdateOne) SetTimes(v int) *LedgerEntryUpdateOne {
	_u.mutation.ResetTimes()
	_u.mutation.SetTimes(v)
	return _u
}

// SetNillableTimes sets the "times" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableTimes(v *int) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetTimes(*v)
	}
	return _u
}

// AddTimes adds value to the "times" field.
func (_u *LedgerEntryUpdateOne) AddTimes(v int) *LedgerEntryUpdateOne {
	_u.mutation.AddTimes(v)
	return _u
}

// ClearTimes clears the value of the "times" field.
func (_u *LedgerEntryUpdateOne) ClearTimes() *LedgerEntryUpdateOne {
	_u.mutation.ClearTimes()
	return _u
}

// SetItemName sets the "item_name" field.
func (_u *LedgerEntryUpdateOne) SetItemName(v string) *LedgerEntryUpdateOne {
	_u.mutation.SetItemName(v)
	return _u
}

// SetNillableItemName sets the "item_name" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableItemName(v *string) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetItemName(*v)
	}
	return _u
}

// ClearItemName clears the value of the "item_name" field.
func (_u *LedgerEntryUpdateOne) ClearItemName() *LedgerEntryUpdateOne {
	_u.mutation.ClearItemName()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *LedgerEntryUpdateOne) SetBalanceAfter(v int) *LedgerEntryUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableBalanceAfter(v *int) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *LedgerEntryUpdateOne) AddBalanceAfter(v int) *LedgerEntryUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *LedgerEntryUpdateOne) ClearBalanceAfter() *LedgerEntryUpdateOne {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetTimesAfter sets the "times_after" field.
func (_u *LedgerEntryUpdateOne) SetTimesAfter(v int) *LedgerEntryUpdateOne {
	_u.mutation.ResetTimesAfter()
	_u.mutation.SetTimesAfter(v)
	return _u
}

// SetNillableTimesAfter sets the "times_after" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableTimesAfter(v *int) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetTimesAfter(*v)
	}
	return _u
}

// AddTimesAfter adds value to the "times_after" field.
func (_u *LedgerEntryUpdateOne) AddTimesAfter(v int) *LedgerEntryUpdateOne {
	_u.mutation.AddTimesAfter(v)
	return _u
}

// ClearTimesAfter clears the value of the "times_after" field.
func (_u *LedgerEntryUpdateOne) ClearTimesAfter() *LedgerEntryUpdateOne {
	_u.mutation.ClearTimesAfter()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *LedgerEntryUpdateOne) SetRemark(v string) *LedgerEntryUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableRemark(v *string) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *LedgerEntryUpdateOne) ClearRemark() *LedgerEntryUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *LedgerEntryUpdateOne) SetOperatorID(v int64) *LedgerEntryUpdateOne {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *LedgerEntryUpdateOne) SetNillableOperatorID(v *int64) *LedgerEntryUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *LedgerEntryUpdateOne) AddOperatorID(v int64) *LedgerEntryUpdateOne {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *LedgerEntryUpdateOne) SetMember(v *Member) *LedgerEntryUpdateOne {
	return _u.SetMemberID(v.ID)
}

// SetCard sets the "card" edge to the MemberCard entity.
func (_u *LedgerEntryUpdateOne) SetCard(v *MemberCard) *LedgerEntryUpdateOne {
	return _u.SetCardID(v.ID)
}

// AddItemIDs adds the "items" edge to the LedgerEntryItem entity by IDs.
func (_u *LedgerEntryUpdateOne) AddItemIDs(ids ...int64) *LedgerEntryUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the LedgerEntryItem entity.
func (_u *LedgerEntryUpdateOne) AddItems(v ...*LedgerEntryItem) *LedgerEntryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the LedgerEntryMutation object of the builder.
func (_u *LedgerEntryUpdateOne) Mutation() *LedgerEntryMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *LedgerEntryUpdateOne) ClearMember() *LedgerEntryUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// ClearCard clears the "card" edge to the MemberCard entity.
func (_u *LedgerEntryUpdateOne) ClearCard() *LedgerEntryUpdateOne {
	_u.mutation.ClearCard()
	return _u
}

// ClearItems clears all "items" edges to the LedgerEntryItem entity.
func (_u *LedgerEntryUpdateOne) ClearItems() *LedgerEntryUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to LedgerEntryItem entities by IDs.
func (_u *LedgerEntryUpdateOne) RemoveItemIDs(ids ...int64) *LedgerEntryUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to LedgerEntryItem entities.
func (_u *LedgerEntryUpdateOne) RemoveItems(v ...*LedgerEntryItem) *LedgerEntryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the LedgerEntryUpdate builder.
func (_u *LedgerEntryUpdateOne) Where(ps ...predicate.LedgerEntry) *LedgerEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LedgerEntryUpdateOne) Select(field string, fields ...string) *LedgerEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LedgerEntry entity.
func (_u *LedgerEntryUpdateOne) Save(ctx context.Context) (*LedgerEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerEntryUpdateOne) SaveX(ctx context.Context) *LedgerEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LedgerEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerEntryUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := ledgerentry.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CardType(); ok {
		if err := ledgerentry.CardTypeValidator(v); err != nil {
			return &ValidationError{Name: "card_type", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.card_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemName(); ok {
		if err := ledgerentry.ItemNameValidator(v); err != nil {
			return &ValidationError{Name: "item_name", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.item_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := ledgerentry.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.remark": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerEntry.member"`)
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerEntry.card"`)
	}
	return nil
}

func (_u *LedgerEntryUpdateOne) sqlSave(ctx context.Context) (_node *LedgerEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgerentry.Table, ledgerentry.Columns, sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LedgerEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledgerentry.FieldID)
		for _, f := range fields {
			if !ledgerentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ledgerentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(ledgerentry.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(ledgerentry.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ledgerentry.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CardType(); ok {
		_spec.SetField(ledgerentry.FieldCardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(ledgerentry.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(ledgerentry.FieldAmount, field.TypeInt, value)
	}
	if _u.mutation.AmountCleared() {
		_spec.ClearField(ledgerentry.FieldAmount, field.TypeInt)
	}
	if value, ok := _u.mutation.Times(); ok {
		_spec.SetField(ledgerentry.FieldTimes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimes(); ok {
		_spec.AddField(ledgerentry.FieldTimes, field.TypeInt, value)
	}
	if _u.mutation.TimesCleared() {
		_spec.ClearField(ledgerentry.FieldTimes, field.TypeInt)
	}
	if value, ok := _u.mutation.ItemName(); ok {
		_spec.SetField(ledgerentry.FieldItemName, field.TypeString, value)
	}
	if _u.mutation.ItemNameCleared() {
		_spec.ClearField(ledgerentry.FieldItemName, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(ledgerentry.FieldBalanceAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(ledgerentry.FieldBalanceAfter, field.TypeInt, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(ledgerentry.FieldBalanceAfter, field.TypeInt)
	}
	if value, ok := _u.mutation.TimesAfter(); ok {
		_spec.SetField(ledgerentry.FieldTimesAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimesAfter(); ok {
		_spec.AddField(ledgerentry.FieldTimesAfter, field.TypeInt, value)
	}
	if _u.mutation.TimesAfterCleared() {
		_spec.ClearField(ledgerentry.FieldTimesAfter, field.TypeInt)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(ledgerentry.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(ledgerentry.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(ledgerentry.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(ledgerentry.FieldOperatorID, field.TypeInt64, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.MemberTable,
			Columns: []string{ledgerentry.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.MemberTable,
			Columns: []string{ledgerentry.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.CardTable,
			Columns: []string{ledgerentry.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.CardTable,
			Columns: []string{ledgerentry.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerentry.ItemsTable,
			Columns: []string{ledgerentry.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentryitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerentry.ItemsTable,
			Columns: []string{ledgerentry.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerentry.ItemsTable,
			Columns: []string{ledgerentry.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LedgerEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgerentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
