// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/carditembalance"
	"card_manager/api_service/ent/ledgerentry"
	"card_manager/api_service/ent/member"
	"card_manager/api_service/ent/membercard"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberCardCreate is the builder for creating a MemberCard entity.
type MemberCardCreate struct {
	config
	mutation *MemberCardMutation
	hooks    []Hook
}

// SetStoreID sets the "store_id" field.
func (_c *MemberCardCreate) SetStoreID(v int64) *MemberCardCreate {
	_c.mutation.SetStoreID(v)
	return _c
}

// SetMemberID sets the "member_id" field.
func (_c *MemberCardCreate) SetMemberID(v int64) *MemberCardCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *MemberCardCreate) SetProductID(v int64) *MemberCardCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *MemberCardCreate) SetType(v string) *MemberCardCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNameSnapshot sets the "name_snapshot" field.
func (_c *MemberCardCreate) SetNameSnapshot(v string) *MemberCardCreate {
	_c.mutation.SetNameSnapshot(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *MemberCardCreate) SetBalance(v int) *MemberCardCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *MemberCardCreate) SetNillableBalance(v *int) *MemberCardCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetRemainTimes sets the "remain_times" field.
func (_c *MemberCardCreate) SetRemainTimes(v int) *MemberCardCreate {
	_c.mutation.SetRemainTimes(v)
	return _c
}

// SetNillableRemainTimes sets the "remain_times" field if the given value is not nil.
func (_c *MemberCardCreate) SetNillableRemainTimes(v *int) *MemberCardCreate {
	if v != nil {
		_c.SetRemainTimes(*v)
	}
	return _c
}

// SetValidFrom sets the "valid_from" field.
func (_c *MemberCardCreate) SetValidFrom(v time.Time) *MemberCardCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_c *MemberCardCreate) SetNillableValidFrom(v *time.Time) *MemberCardCreate {
	if v != nil {
		_c.SetValidFrom(*v)
	}
	return _c
}

// SetValidTo sets the "valid_to" field.
func (_c *MemberCardCreate) SetValidTo(v time.Time) *MemberCardCreate {
	_c.mutation.SetValidTo(v)
	return _c
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_c *MemberCardCreate) SetNillableValidTo(v *time.Time) *MemberCardCreate {
	if v != nil {
		_c.SetValidTo(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MemberCardCreate) SetStatus(v string) *MemberCardCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MemberCardCreate) SetNillableStatus(v *string) *MemberCardCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOpenedBy sets the "opened_by" field.
func (_c *MemberCardCreate) SetOpenedBy(v int64) *MemberCardCreate {
	_c.mutation.SetOpenedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemberCardCreate) SetCreatedAt(v time.Time) *MemberCardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemberCardCreate) SetNillableCreatedAt(v *time.Time) *MemberCardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MemberCardCreate) SetUpdatedAt(v time.Time) *MemberCardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MemberCardCreate) SetNillableUpdatedAt(v *time.Time) *MemberCardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemberCardCreate) SetID(v int64) *MemberCardCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetMember sets the "member" edge to the Member entity.
func (_c *MemberCardCreate) SetMember(v *Member) *MemberCardCreate {
	return _c.SetMemberID(v.ID)
}

// AddItemBalanceIDs adds the "item_balances" edge to the CardItemBalance entity by IDs.
func (_c *MemberCardCreate) AddItemBalanceIDs(ids ...int64) *MemberCardCreate {
	_c.mutation.AddItemBalanceIDs(ids...)
	return _c
}

// AddItemBalances adds the "item_balances" edges to the CardItemBalance entity.
func (_c *MemberCardCreate) AddItemBalances(v ...*CardItemBalance) *MemberCardCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemBalanceIDs(ids...)
}

// AddLedgerIDs adds the "ledgers" edge to the LedgerEntry entity by IDs.
func (_c *MemberCardCreate) AddLedgerIDs(ids ...int64) *MemberCardCreate {
	_c.mutation.AddLedgerIDs(ids...)
	return _c
}

// AddLedgers adds the "ledgers" edges to the LedgerEntry entity.
func (_c *MemberCardCreate) AddLedgers(v ...*LedgerEntry) *MemberCardCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLedgerIDs(ids...)
}

// Mutation returns the MemberCardMutation object of the builder.
func (_c *MemberCardCreate) Mutation() *MemberCardMutation {
	return _c.mutation
}

// Save creates the MemberCard in the database.
func (_c *MemberCardCreate) Save(ctx context.Context) (*MemberCard, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberCardCreate) SaveX(ctx context.Context) *MemberCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberCardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberCardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberCardCreate) defaults() {
	if _, ok := _c.mutation.Balance(); !ok {
		v := membercard.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := membercard.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := membercard.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := membercard.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberCardCreate) check() error {
	if _, ok := _c.mutation.StoreID(); !ok {
		return &ValidationError{Name: "store_id", err: errors.New(`ent: missing required field "MemberCard.store_id"`)}
	}
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "MemberCard.member_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "MemberCard.product_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MemberCard.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := membercard.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MemberCard.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameSnapshot(); !ok {
		return &ValidationError{Name: "name_snapshot", err: errors.New(`ent: missing required field "MemberCard.name_snapshot"`)}
	}
	if v, ok := _c.mutation.NameSnapshot(); ok {
		if err := membercard.NameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MemberCard.name_snapshot": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "MemberCard.balance"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MemberCard.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := membercard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MemberCard.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpenedBy(); !ok {
		return &ValidationError{Name: "opened_by", err: errors.New(`ent: missing required field "MemberCard.opened_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MemberCard.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MemberCard.updated_at"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "MemberCard.member"`)}
	}
	return nil
}

func (_c *MemberCardCreate) sqlSave(ctx context.Context) (*MemberCard, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberCardCreate) createSpec() (*MemberCard, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberCard{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(membercard.Table, sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StoreID(); ok {
		_spec.SetField(membercard.FieldStoreID, field.TypeInt64, value)
		_node.StoreID = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(membercard.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(membercard.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.NameSnapshot(); ok {
		_spec.SetField(membercard.FieldNameSnapshot, field.TypeString, value)
		_node.NameSnapshot = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(membercard.FieldBalance, field.TypeInt, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.RemainTimes(); ok {
		_spec.SetField(membercard.FieldRemainTimes, field.TypeInt, value)
		_node.RemainTimes = &value
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(membercard.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = &value
	}
	if value, ok := _c.mutation.ValidTo(); ok {
		_spec.SetField(membercard.FieldValidTo, field.TypeTime, value)
		_node.ValidTo = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(membercard.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.OpenedBy(); ok {
		_spec.SetField(membercard.FieldOpenedBy, field.TypeInt64, value)
		_node.OpenedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(membercard.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(membercard.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membercard.MemberTable,
			Columns: []string{membercard.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.ItemBalancesTable,
			Columns: []string{membercard.ItemBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carditembalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.LedgersTable,
			Columns: []string{membercard.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberCardCreateBulk is the builder for creating many MemberCard entities in bulk.
type MemberCardCreateBulk struct {
	config
	err      error
	builders []*MemberCardCreate
}

// Save creates the MemberCard entities in the database.
func (_c *MemberCardCreateBulk) Save(ctx context.Context) ([]*MemberCard, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberCard, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberCardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberCardCreateBulk) SaveX(ctx context.Context) []*MemberCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberCardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberCardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
