// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/carditembalance"
	"card_manager/api_service/ent/ledgerentry"
	"card_manager/api_service/ent/member"
	"card_manager/api_service/ent/membercard"
	"card_manager/api_service/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberCardUpdate is the builder for updating MemberCard entities.
type MemberCardUpdate struct {
	config
	hooks    []Hook
	mutation *MemberCardMutation
}

// Where appends a list predicates to the MemberCardUpdate builder.
func (_u *MemberCardUpdate) Where(ps ...predicate.MemberCard) *MemberCardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *MemberCardUpdate) SetStoreID(v int64) *MemberCardUpdate {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableStoreID(v *int64) *MemberCardUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *MemberCardUpdate) AddStoreID(v int64) *MemberCardUpdate {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *MemberCardUpdate) SetMemberID(v int64) *MemberCardUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableMemberID(v *int64) *MemberCardUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *MemberCardUpdate) SetProductID(v int64) *MemberCardUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableProductID(v *int64) *MemberCardUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *MemberCardUpdate) AddProductID(v int64) *MemberCardUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *MemberCardUpdate) SetType(v string) *MemberCardUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableType(v *string) *MemberCardUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNameSnapshot sets the "name_snapshot" field.
func (_u *MemberCardUpdate) SetNameSnapshot(v string) *MemberCardUpdate {
	_u.mutation.SetNameSnapshot(v)
	return _u
}

// SetNillableNameSnapshot sets the "name_snapshot" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableNameSnapshot(v *string) *MemberCardUpdate {
	if v != nil {
		_u.SetNameSnapshot(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *MemberCardUpdate) SetBalance(v int) *MemberCardUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableBalance(v *int) *MemberCardUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *MemberCardUpdate) AddBalance(v int) *MemberCardUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetRemainTimes sets the "remain_times" field.
func (_u *MemberCardUpdate) SetRemainTimes(v int) *MemberCardUpdate {
	_u.mutation.ResetRemainTimes()
	_u.mutation.SetRemainTimes(v)
	return _u
}

// SetNillableRemainTimes sets the "remain_times" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableRemainTimes(v *int) *MemberCardUpdate {
	if v != nil {
		_u.SetRemainTimes(*v)
	}
	return _u
}

// AddRemainTimes adds value to the "remain_times" field.
func (_u *MemberCardUpdate) AddRemainTimes(v int) *MemberCardUpdate {
	_u.mutation.AddRemainTimes(v)
	return _u
}

// ClearRemainTimes clears the value of the "remain_times" field.
func (_u *MemberCardUpdate) ClearRemainTimes() *MemberCardUpdate {
	_u.mutation.ClearRemainTimes()
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *MemberCardUpdate) SetValidFrom(v time.Time) *MemberCardUpdate {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableValidFrom(v *time.Time) *MemberCardUpdate {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *MemberCardUpdate) ClearValidFrom() *MemberCardUpdate {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *MemberCardUpdate) SetValidTo(v time.Time) *MemberCardUpdate {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableValidTo(v *time.Time) *MemberCardUpdate {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *MemberCardUpdate) ClearValidTo() *MemberCardUpdate {
	_u.mutation.ClearValidTo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemberCardUpdate) SetStatus(v string) *MemberCardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableStatus(v *string) *MemberCardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOpenedBy sets the "opened_by" field.
func (_u *MemberCardUpdate) SetOpenedBy(v int64) *MemberCardUpdate {
	_u.mutation.ResetOpenedBy()
	_u.mutation.SetOpenedBy(v)
	return _u
}

// SetNillableOpenedBy sets the "opened_by" field if the given value is not nil.
func (_u *MemberCardUpdate) SetNillableOpenedBy(v *int64) *MemberCardUpdate {
	if v != nil {
		_u.SetOpenedBy(*v)
	}
	return _u
}

// AddOpenedBy adds value to the "opened_by" field.
func (_u *MemberCardUpdate) AddOpenedBy(v int64) *MemberCardUpdate {
	_u.mutation.AddOpenedBy(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberCardUpdate) SetUpdatedAt(v time.Time) *MemberCardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *MemberCardUpdate) SetMember(v *Member) *MemberCardUpdate {
	return _u.SetMemberID(v.ID)
}

// AddItemBalanceIDs adds the "item_balances" edge to the CardItemBalance entity by IDs.
func (_u *MemberCardUpdate) AddItemBalanceIDs(ids ...int64) *MemberCardUpdate {
	_u.mutation.AddItemBalanceIDs(ids...)
	return _u
}

// AddItemBalances adds the "item_balances" edges to the CardItemBalance entity.
func (_u *MemberCardUpdate) AddItemBalances(v ...*CardItemBalance) *MemberCardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemBalanceIDs(ids...)
}

// AddLedgerIDs adds the "ledgers" edge to the LedgerEntry entity by IDs.
func (_u *MemberCardUpdate) AddLedgerIDs(ids ...int64) *MemberCardUpdate {
	_u.mutation.AddLedgerIDs(ids...)
	return _u
}

// AddLedgers adds the "ledgers" edges to the LedgerEntry entity.
func (_u *MemberCardUpdate) AddLedgers(v ...*LedgerEntry) *MemberCardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerIDs(ids...)
}

// Mutation returns the MemberCardMutation object of the builder.
func (_u *MemberCardUpdate) Mutation() *MemberCardMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *MemberCardUpdate) ClearMember() *MemberCardUpdate {
	_u.mutation.ClearMember()
	return _u
}

// ClearItemBalances clears all "item_balances" edges to the CardItemBalance entity.
func (_u *MemberCardUpdate) ClearItemBalances() *MemberCardUpdate {
	_u.mutation.ClearItemBalances()
	return _u
}

// RemoveItemBalanceIDs removes the "item_balances" edge to CardItemBalance entities by IDs.
func (_u *MemberCardUpdate) RemoveItemBalanceIDs(ids ...int64) *MemberCardUpdate {
	_u.mutation.RemoveItemBalanceIDs(ids...)
	return _u
}

// RemoveItemBalances removes "item_balances" edges to CardItemBalance entities.
func (_u *MemberCardUpdate) RemoveItemBalances(v ...*CardItemBalance) *MemberCardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemBalanceIDs(ids...)
}

// ClearLedgers clears all "ledgers" edges to the LedgerEntry entity.
func (_u *MemberCardUpdate) ClearLedgers() *MemberCardUpdate {
	_u.mutation.ClearLedgers()
	return _u
}

// RemoveLedgerIDs removes the "ledgers" edge to LedgerEntry entities by IDs.
func (_u *MemberCardUpdate) RemoveLedgerIDs(ids ...int64) *MemberCardUpdate {
	_u.mutation.RemoveLedgerIDs(ids...)
	return _u
}

// RemoveLedgers removes "ledgers" edges to LedgerEntry entities.
func (_u *MemberCardUpdate) RemoveLedgers(v ...*LedgerEntry) *MemberCardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberCardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberCardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberCardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberCardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberCardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := membercard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberCardUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := membercard.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MemberCard.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameSnapshot(); ok {
		if err := membercard.NameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MemberCard.name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := membercard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MemberCard.status": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberCard.member"`)
	}
	return nil
}

func (_u *MemberCardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membercard.Table, membercard.Columns, sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(membercard.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(membercard.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(membercard.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(membercard.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(membercard.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameSnapshot(); ok {
		_spec.SetField(membercard.FieldNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(membercard.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(membercard.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RemainTimes(); ok {
		_spec.SetField(membercard.FieldRemainTimes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRemainTimes(); ok {
		_spec.AddField(membercard.FieldRemainTimes, field.TypeInt, value)
	}
	if _u.mutation.RemainTimesCleared() {
		_spec.ClearField(membercard.FieldRemainTimes, field.TypeInt)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(membercard.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(membercard.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(membercard.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(membercard.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(membercard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenedBy(); ok {
		_spec.SetField(membercard.FieldOpenedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOpenedBy(); ok {
		_spec.AddField(membercard.FieldOpenedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(membercard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membercard.MemberTable,
			Columns: []string{membercard.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membercard.MemberTable,
			Columns: []string{membercard.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.ItemBalancesTable,
			Columns: []string{membercard.ItemBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carditembalance.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemBalancesIDs(); len(nodes) > 0 && !_u.mutation.ItemBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.ItemBalancesTable,
			Columns: []string{membercard.ItemBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carditembalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.ItemBalancesTable,
			Columns: []string{membercard.ItemBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carditembalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.LedgersTable,
			Columns: []string{membercard.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !_u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.LedgersTable,
			Columns: []string{membercard.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.LedgersTable,
			Columns: []string{membercard.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membercard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberCardUpdateOne is the builder for updating a single MemberCard entity.
type MemberCardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberCardMutation
}

// SetStoreID sets the "store_id" field.
func (_u *MemberCardUpdateOne) SetStoreID(v int64) *MemberCardUpdateOne {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableStoreID(v *int64) *MemberCardUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *MemberCardUpdateOne) AddStoreID(v int64) *MemberCardUpdateOne {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *MemberCardUpdateOne) SetMemberID(v int64) *MemberCardUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableMemberID(v *int64) *MemberCardUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *MemberCardUpdateOne) SetProductID(v int64) *MemberCardUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableProductID(v *int64) *MemberCardUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *MemberCardUpdateOne) AddProductID(v int64) *MemberCardUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *MemberCardUpdateOne) SetType(v string) *MemberCardUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableType(v *string) *MemberCardUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNameSnapshot sets the "name_snapshot" field.
func (_u *MemberCardUpdateOne) SetNameSnapshot(v string) *MemberCardUpdateOne {
	_u.mutation.SetNameSnapshot(v)
	return _u
}

// SetNillableNameSnapshot sets the "name_snapshot" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableNameSnapshot(v *string) *MemberCardUpdateOne {
	if v != nil {
		_u.SetNameSnapshot(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *MemberCardUpdateOne) SetBalance(v int) *MemberCardUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableBalance(v *int) *MemberCardUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *MemberCardUpdateOne) AddBalance(v int) *MemberCardUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetRemainTimes sets the "remain_times" field.
func (_u *MemberCardUpdateOne) SetRemainTimes(v int) *MemberCardUpdateOne {
	_u.mutation.ResetRemainTimes()
	_u.mutation.SetRemainTimes(v)
	return _u
}

// SetNillableRemainTimes sets the "remain_times" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableRemainTimes(v *int) *MemberCardUpdateOne {
	if v != nil {
		_u.SetRemainTimes(*v)
	}
	return _u
}

// AddRemainTimes adds value to the "remain_times" field.
func (_u *MemberCardUpdateOne) AddRemainTimes(v int) *MemberCardUpdateOne {
	_u.mutation.AddRemainTimes(v)
	return _u
}

// ClearRemainTimes clears the value of the "remain_times" field.
func (_u *MemberCardUpdateOne) ClearRemainTimes() *MemberCardUpdateOne {
	_u.mutation.ClearRemainTimes()
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *MemberCardUpdateOne) SetValidFrom(v time.Time) *MemberCardUpdateOne {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableValidFrom(v *time.Time) *MemberCardUpdateOne {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *MemberCardUpdateOne) ClearValidFrom() *MemberCardUpdateOne {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *MemberCardUpdateOne) SetValidTo(v time.Time) *MemberCardUpdateOne {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableValidTo(v *time.Time) *MemberCardUpdateOne {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *MemberCardUpdateOne) ClearValidTo() *MemberCardUpdateOne {
	_u.mutation.ClearValidTo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemberCardUpdateOne) SetStatus(v string) *MemberCardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableStatus(v *string) *MemberCardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOpenedBy sets the "opened_by" field.
func (_u *MemberCardUpdateOne) SetOpenedBy(v int64) *MemberCardUpdateOne {
	_u.mutation.ResetOpenedBy()
	_u.mutation.SetOpenedBy(v)
	return _u
}

// SetNillableOpenedBy sets the "opened_by" field if the given value is not nil.
func (_u *MemberCardUpdateOne) SetNillableOpenedBy(v *int64) *MemberCardUpdateOne {
	if v != nil {
		_u.SetOpenedBy(*v)
	}
	return _u
}

// AddOpenedBy adds value to the "opened_by" field.
func (_u *MemberCardUpdateOne) AddOpenedBy(v int64) *MemberCardUpdateOne {
	_u.mutation.AddOpenedBy(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberCardUpdateOne) SetUpdatedAt(v time.Time) *MemberCardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *MemberCardUpdateOne) SetMember(v *Member) *MemberCardUpdateOne {
	return _u.SetMemberID(v.ID)
}

// AddItemBalanceIDs adds the "item_balances" edge to the CardItemBalance entity by IDs.
func (_u *MemberCardUpdateOne) AddItemBalanceIDs(ids ...int64) *MemberCardUpdateOne {
	_u.mutation.AddItemBalanceIDs(ids...)
	return _u
}

// AddItemBalances adds the "item_balances" edges to the CardItemBalance entity.
func (_u *MemberCardUpdateOne) AddItemBalances(v ...*CardItemBalance) *MemberCardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemBalanceIDs(ids...)
}

// AddLedgerIDs adds the "ledgers" edge to the LedgerEntry entity by IDs.
func (_u *MemberCardUpdateOne) AddLedgerIDs(ids ...int64) *MemberCardUpdateOne {
	_u.mutation.AddLedgerIDs(ids...)
	return _u
}

// AddLedgers adds the "ledgers" edges to the LedgerEntry entity.
func (_u *MemberCardUpdateOne) AddLedgers(v ...*LedgerEntry) *MemberCardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerIDs(ids...)
}

// Mutation returns the MemberCardMutation object of the builder.
func (_u *MemberCardUpdateOne) Mutation() *MemberCardMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *MemberCardUpdateOne) ClearMember() *MemberCardUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// ClearItemBalances clears all "item_balances" edges to the CardItemBalance entity.
func (_u *MemberCardUpdateOne) ClearItemBalances() *MemberCardUpdateOne {
	_u.mutation.ClearItemBalances()
	return _u
}

// RemoveItemBalanceIDs removes the "item_balances" edge to CardItemBalance entities by IDs.
func (_u *MemberCardUpdateOne) RemoveItemBalanceIDs(ids ...int64) *MemberCardUpdateOne {
	_u.mutation.RemoveItemBalanceIDs(ids...)
	return _u
}

// RemoveItemBalances removes "item_balances" edges to CardItemBalance entities.
func (_u *MemberCardUpdateOne) RemoveItemBalances(v ...*CardItemBalance) *MemberCardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemBalanceIDs(ids...)
}

// ClearLedgers clears all "ledgers" edges to the LedgerEntry entity.
func (_u *MemberCardUpdateOne) ClearLedgers() *MemberCardUpdateOne {
	_u.mutation.ClearLedgers()
	return _u
}

// RemoveLedgerIDs removes the "ledgers" edge to LedgerEntry entities by IDs.
func (_u *MemberCardUpdateOne) RemoveLedgerIDs(ids ...int64) *MemberCardUpdateOne {
	_u.mutation.RemoveLedgerIDs(ids...)
	return _u
}

// RemoveLedgers removes "ledgers" edges to LedgerEntry entities.
func (_u *MemberCardUpdateOne) RemoveLedgers(v ...*LedgerEntry) *MemberCardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerIDs(ids...)
}

// Where appends a list predicates to the MemberCardUpdate builder.
func (_u *MemberCardUpdateOne) Where(ps ...predicate.MemberCard) *MemberCardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberCardUpdateOne) Select(field string, fields ...string) *MemberCardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberCard entity.
func (_u *MemberCardUpdateOne) Save(ctx context.Context) (*MemberCard, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberCardUpdateOne) SaveX(ctx context.Context) *MemberCard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberCardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberCardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberCardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := membercard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberCardUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := membercard.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MemberCard.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameSnapshot(); ok {
		if err := membercard.NameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MemberCard.name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := membercard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MemberCard.status": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberCard.member"`)
	}
	return nil
}

func (_u *MemberCardUpdateOne) sqlSave(ctx context.Context) (_node *MemberCard, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membercard.Table, membercard.Columns, sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberCard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, membercard.FieldID)
		for _, f := range fields {
			if !membercard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != membercard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(membercard.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(membercard.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(membercard.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(membercard.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(membercard.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameSnapshot(); ok {
		_spec.SetField(membercard.FieldNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(membercard.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(membercard.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RemainTimes(); ok {
		_spec.SetField(membercard.FieldRemainTimes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRemainTimes(); ok {
		_spec.AddField(membercard.FieldRemainTimes, field.TypeInt, value)
	}
	if _u.mutation.RemainTimesCleared() {
		_spec.ClearField(membercard.FieldRemainTimes, field.TypeInt)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(membercard.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(membercard.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(membercard.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(membercard.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(membercard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenedBy(); ok {
		_spec.SetField(membercard.FieldOpenedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOpenedBy(); ok {
		_spec.AddField(membercard.FieldOpenedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(membercard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membercard.MemberTable,
			Columns: []string{membercard.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membercard.MemberTable,
			Columns: []string{membercard.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.ItemBalancesTable,
			Columns: []string{membercard.ItemBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carditembalance.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemBalancesIDs(); len(nodes) > 0 && !_u.mutation.ItemBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.ItemBalancesTable,
			Columns: []string{membercard.ItemBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carditembalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.ItemBalancesTable,
			Columns: []string{membercard.ItemBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carditembalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.LedgersTable,
			Columns: []string{membercard.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !_u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.LedgersTable,
			Columns: []string{membercard.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   membercard.LedgersTable,
			Columns: []string{membercard.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemberCard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membercard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
