// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/ledgerentry"
	"card_manager/api_service/ent/member"
	"card_manager/api_service/ent/membercard"
	"card_manager/api_service/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *MemberUpdate) SetStoreID(v int64) *MemberUpdate {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableStoreID(v *int64) *MemberUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *MemberUpdate) AddStoreID(v int64) *MemberUpdate {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *MemberUpdate) SetName(v string) *MemberUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableName(v *string) *MemberUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *MemberUpdate) SetPhone(v string) *MemberUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *MemberUpdate) SetNillablePhone(v *string) *MemberUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *MemberUpdate) SetSource(v string) *MemberUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableSource(v *string) *MemberUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *MemberUpdate) ClearSource() *MemberUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberUpdate) SetUpdatedAt(v time.Time) *MemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCardIDs adds the "cards" edge to the MemberCard entity by IDs.
func (_u *MemberUpdate) AddCardIDs(ids ...int64) *MemberUpdate {
	_u.mutation.AddCardIDs(ids...)
	return _u
}

// AddCards adds the "cards" edges to the MemberCard entity.
func (_u *MemberUpdate) AddCards(v ...*MemberCard) *MemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCardIDs(ids...)
}

// AddLedgerIDs adds the "ledgers" edge to the LedgerEntry entity by IDs.
func (_u *MemberUpdate) AddLedgerIDs(ids ...int64) *MemberUpdate {
	_u.mutation.AddLedgerIDs(ids...)
	return _u
}

// AddLedgers adds the "ledgers" edges to the LedgerEntry entity.
func (_u *MemberUpdate) AddLedgers(v ...*LedgerEntry) *MemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdate) Mutation() *MemberMutation {
	return _u.mutation
}

// ClearCards clears all "cards" edges to the MemberCard entity.
func (_u *MemberUpdate) ClearCards() *MemberUpdate {
	_u.mutation.ClearCards()
	return _u
}

// RemoveCardIDs removes the "cards" edge to MemberCard entities by IDs.
func (_u *MemberUpdate) RemoveCardIDs(ids ...int64) *MemberUpdate {
	_u.mutation.RemoveCardIDs(ids...)
	return _u
}

// RemoveCards removes "cards" edges to MemberCard entities.
func (_u *MemberUpdate) RemoveCards(v ...*MemberCard) *MemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCardIDs(ids...)
}

// ClearLedgers clears all "ledgers" edges to the LedgerEntry entity.
func (_u *MemberUpdate) ClearLedgers() *MemberUpdate {
	_u.mutation.ClearLedgers()
	return _u
}

// RemoveLedgerIDs removes the "ledgers" edge to LedgerEntry entities by IDs.
func (_u *MemberUpdate) RemoveLedgerIDs(ids ...int64) *MemberUpdate {
	_u.mutation.RemoveLedgerIDs(ids...)
	return _u
}

// RemoveLedgers removes "ledgers" edges to LedgerEntry entities.
func (_u *MemberUpdate) RemoveLedgers(v ...*LedgerEntry) *MemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := member.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := member.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Member.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := member.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Member.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := member.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Member.source": %w`, err)}
		}
	}
	return nil
}

func (_u *MemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(member.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(member.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(member.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(member.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(member.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(member.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.CardsTable,
			Columns: []string{member.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCardsIDs(); len(nodes) > 0 && !_u.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.CardsTable,
			Columns: []string{member.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.CardsTable,
			Columns: []string{member.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.LedgersTable,
			Columns: []string{member.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !_u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.LedgersTable,
			Columns: []string{member.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.LedgersTable,
			Columns: []string{member.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberMutation
}

// SetStoreID sets the "store_id" field.
func (_u *MemberUpdateOne) SetStoreID(v int64) *MemberUpdateOne {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableStoreID(v *int64) *MemberUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *MemberUpdateOne) AddStoreID(v int64) *MemberUpdateOne {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *MemberUpdateOne) SetName(v string) *MemberUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableName(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *MemberUpdateOne) SetPhone(v string) *MemberUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillablePhone(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *MemberUpdateOne) SetSource(v string) *MemberUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableSource(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *MemberUpdateOne) ClearSource() *MemberUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberUpdateOne) SetUpdatedAt(v time.Time) *MemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCardIDs adds the "cards" edge to the MemberCard entity by IDs.
func (_u *MemberUpdateOne) AddCardIDs(ids ...int64) *MemberUpdateOne {
	_u.mutation.AddCardIDs(ids...)
	return _u
}

// AddCards adds the "cards" edges to the MemberCard entity.
func (_u *MemberUpdateOne) AddCards(v ...*MemberCard) *MemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCardIDs(ids...)
}

// AddLedgerIDs adds the "ledgers" edge to the LedgerEntry entity by IDs.
func (_u *MemberUpdateOne) AddLedgerIDs(ids ...int64) *MemberUpdateOne {
	_u.mutation.AddLedgerIDs(ids...)
	return _u
}

// AddLedgers adds the "ledgers" edges to the LedgerEntry entity.
func (_u *MemberUpdateOne) AddLedgers(v ...*LedgerEntry) *MemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdateOne) Mutation() *MemberMutation {
	return _u.mutation
}

// ClearCards clears all "cards" edges to the MemberCard entity.
func (_u *MemberUpdateOne) ClearCards() *MemberUpdateOne {
	_u.mutation.ClearCards()
	return _u
}

// RemoveCardIDs removes the "cards" edge to MemberCard entities by IDs.
func (_u *MemberUpdateOne) RemoveCardIDs(ids ...int64) *MemberUpdateOne {
	_u.mutation.RemoveCardIDs(ids...)
	return _u
}

// RemoveCards removes "cards" edges to MemberCard entities.
func (_u *MemberUpdateOne) RemoveCards(v ...*MemberCard) *MemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCardIDs(ids...)
}

// ClearLedgers clears all "ledgers" edges to the LedgerEntry entity.
func (_u *MemberUpdateOne) ClearLedgers() *MemberUpdateOne {
	_u.mutation.ClearLedgers()
	return _u
}

// RemoveLedgerIDs removes the "ledgers" edge to LedgerEntry entities by IDs.
func (_u *MemberUpdateOne) RemoveLedgerIDs(ids ...int64) *MemberUpdateOne {
	_u.mutation.RemoveLedgerIDs(ids...)
	return _u
}

// RemoveLedgers removes "ledgers" edges to LedgerEntry entities.
func (_u *MemberUpdateOne) RemoveLedgers(v ...*LedgerEntry) *MemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerIDs(ids...)
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdateOne) Where(ps ...predicate.Member) *MemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberUpdateOne) Select(field string, fields ...string) *MemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Member entity.
func (_u *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := member.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := member.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Member.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := member.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Member.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := member.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Member.source": %w`, err)}
		}
	}
	return nil
}

func (_u *MemberUpdateOne) sqlSave(ctx context.Context) (_node *Member, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Member.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, member.FieldID)
		for _, f := range fields {
			if !member.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != member.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(member.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(member.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(member.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(member.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(member.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(member.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.CardsTable,
			Columns: []string{member.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCardsIDs(); len(nodes) > 0 && !_u.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.CardsTable,
			Columns: []string{member.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.CardsTable,
			Columns: []string{member.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membercard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.LedgersTable,
			Columns: []string{member.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !_u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.LedgersTable,
			Columns: []string{member.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.LedgersTable,
			Columns: []string{member.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Member{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
