// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/oauthidentity"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OAuthIdentity is the model entity for the OAuthIdentity schema.
type OAuthIdentity struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderUID holds the value of the "provider_uid" field.
	ProviderUID string `json:"provider_uid,omitempty"`
	// UnionID holds the value of the "union_id" field.
	UnionID *string `json:"union_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Nickname holds the value of the "nickname" field.
	Nickname *string `json:"nickname,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL *string `json:"avatar_url,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra map[string]interface{} `json:"extra,omitempty"`
	// AuthorizedAt holds the value of the "authorized_at" field.
	AuthorizedAt time.Time `json:"authorized_at,omitempty"`
	// BoundAt holds the value of the "bound_at" field.
	BoundAt *time.Time `json:"bound_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthIdentity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthidentity.FieldExtra:
			values[i] = new([]byte)
		case oauthidentity.FieldID, oauthidentity.FieldUserID:
			values[i] = new(sql.NullInt64)
		case oauthidentity.FieldProvider, oauthidentity.FieldProviderUID, oauthidentity.FieldUnionID, oauthidentity.FieldNickname, oauthidentity.FieldAvatarURL:
			values[i] = new(sql.NullString)
		case oauthidentity.FieldAuthorizedAt, oauthidentity.FieldBoundAt, oauthidentity.FieldCreatedAt, oauthidentity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthIdentity fields.
func (_m *OAuthIdentity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthidentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthidentity.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case oauthidentity.FieldProviderUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_uid", values[i])
			} else if value.Valid {
				_m.ProviderUID = value.String
			}
		case oauthidentity.FieldUnionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field union_id", values[i])
			} else if value.Valid {
				_m.UnionID = new(string)
				*_m.UnionID = value.String
			}
		case oauthidentity.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case oauthidentity.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				_m.Nickname = new(string)
				*_m.Nickname = value.String
			}
		case oauthidentity.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = new(string)
				*_m.AvatarURL = value.String
			}
		case oauthidentity.FieldExtra:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Extra); err != nil {
					return fmt.Errorf("unmarshal field extra: %w", err)
				}
			}
		case oauthidentity.FieldAuthorizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field authorized_at", values[i])
			} else if value.Valid {
				_m.AuthorizedAt = value.Time
			}
		case oauthidentity.FieldBoundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bound_at", values[i])
			} else if value.Valid {
				_m.BoundAt = new(time.Time)
				*_m.BoundAt = value.Time
			}
		case oauthidentity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthidentity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthIdentity.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthIdentity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthIdentity.
// Note that you need to call OAuthIdentity.Unwrap() before calling this method if this OAuthIdentity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthIdentity) Update() *OAuthIdentityUpdateOne {
	return NewOAuthIdentityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthIdentity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthIdentity) Unwrap() *OAuthIdentity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthIdentity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthIdentity) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthIdentity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_uid=")
	builder.WriteString(_m.ProviderUID)
	builder.WriteString(", ")
	if v := _m.UnionID; v != nil {
		builder.WriteString("union_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.Nickname; v != nil {
		builder.WriteString("nickname=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AvatarURL; v != nil {
		builder.WriteString("avatar_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("extra=")
	builder.WriteString(fmt.Sprintf("%v", _m.Extra))
	builder.WriteString(", ")
	builder.WriteString("authorized_at=")
	builder.WriteString(_m.AuthorizedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.BoundAt; v != nil {
		builder.WriteString("bound_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthIdentities is a parsable slice of OAuthIdentity.
type OAuthIdentities []*OAuthIdentity
