// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/oauthidentity"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthIdentityCreate is the builder for creating a OAuthIdentity entity.
type OAuthIdentityCreate struct {
	config
	mutation *OAuthIdentityMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *OAuthIdentityCreate) SetProvider(v string) *OAuthIdentityCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProviderUID sets the "provider_uid" field.
func (_c *OAuthIdentityCreate) SetProviderUID(v string) *OAuthIdentityCreate {
	_c.mutation.SetProviderUID(v)
	return _c
}

// SetUnionID sets the "union_id" field.
func (_c *OAuthIdentityCreate) SetUnionID(v string) *OAuthIdentityCreate {
	_c.mutation.SetUnionID(v)
	return _c
}

// SetNillableUnionID sets the "union_id" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableUnionID(v *string) *OAuthIdentityCreate {
	if v != nil {
		_c.SetUnionID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthIdentityCreate) SetUserID(v int64) *OAuthIdentityCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableUserID(v *int64) *OAuthIdentityCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *OAuthIdentityCreate) SetNickname(v string) *OAuthIdentityCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableNickname(v *string) *OAuthIdentityCreate {
	if v != nil {
		_c.SetNickname(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *OAuthIdentityCreate) SetAvatarURL(v string) *OAuthIdentityCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableAvatarURL(v *string) *OAuthIdentityCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetExtra sets the "extra" field.
func (_c *OAuthIdentityCreate) SetExtra(v map[string]interface{}) *OAuthIdentityCreate {
	_c.mutation.SetExtra(v)
	return _c
}

// SetAuthorizedAt sets the "authorized_at" field.
func (_c *OAuthIdentityCreate) SetAuthorizedAt(v time.Time) *OAuthIdentityCreate {
	_c.mutation.SetAuthorizedAt(v)
	return _c
}

// SetNillableAuthorizedAt sets the "authorized_at" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableAuthorizedAt(v *time.Time) *OAuthIdentityCreate {
	if v != nil {
		_c.SetAuthorizedAt(*v)
	}
	return _c
}

// SetBoundAt sets the "bound_at" field.
func (_c *OAuthIdentityCreate) SetBoundAt(v time.Time) *OAuthIdentityCreate {
	_c.mutation.SetBoundAt(v)
	return _c
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableBoundAt(v *time.Time) *OAuthIdentityCreate {
	if v != nil {
		_c.SetBoundAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthIdentityCreate) SetCreatedAt(v time.Time) *OAuthIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableCreatedAt(v *time.Time) *OAuthIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthIdentityCreate) SetUpdatedAt(v time.Time) *OAuthIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthIdentityCreate) SetNillableUpdatedAt(v *time.Time) *OAuthIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthIdentityCreate) SetID(v int64) *OAuthIdentityCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OAuthIdentityMutation object of the builder.
func (_c *OAuthIdentityCreate) Mutation() *OAuthIdentityMutation {
	return _c.mutation
}

// Save creates the OAuthIdentity in the database.
func (_c *OAuthIdentityCreate) Save(ctx context.Context) (*OAuthIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthIdentityCreate) SaveX(ctx context.Context) *OAuthIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthIdentityCreate) defaults() {
	if _, ok := _c.mutation.UserID(); !ok {
		v := oauthidentity.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.AuthorizedAt(); !ok {
		v := oauthidentity.DefaultAuthorizedAt()
		_c.mutation.SetAuthorizedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthidentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthidentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthIdentityCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "OAuthIdentity.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := oauthidentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderUID(); !ok {
		return &ValidationError{Name: "provider_uid", err: errors.New(`ent: missing required field "OAuthIdentity.provider_uid"`)}
	}
	if v, ok := _c.mutation.ProviderUID(); ok {
		if err := oauthidentity.ProviderUIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_uid", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.provider_uid": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UnionID(); ok {
		if err := oauthidentity.UnionIDValidator(v); err != nil {
			return &ValidationError{Name: "union_id", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.union_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthIdentity.user_id"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := oauthidentity.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.nickname": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AvatarURL(); ok {
		if err := oauthidentity.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.avatar_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorizedAt(); !ok {
		return &ValidationError{Name: "authorized_at", err: errors.New(`ent: missing required field "OAuthIdentity.authorized_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthIdentity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthIdentity.updated_at"`)}
	}
	return nil
}

func (_c *OAuthIdentityCreate) sqlSave(ctx context.Context) (*OAuthIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthIdentityCreate) createSpec() (*OAuthIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthidentity.Table, sqlgraph.NewFieldSpec(oauthidentity.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(oauthidentity.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderUID(); ok {
		_spec.SetField(oauthidentity.FieldProviderUID, field.TypeString, value)
		_node.ProviderUID = value
	}
	if value, ok := _c.mutation.UnionID(); ok {
		_spec.SetField(oauthidentity.FieldUnionID, field.TypeString, value)
		_node.UnionID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauthidentity.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(oauthidentity.FieldNickname, field.TypeString, value)
		_node.Nickname = &value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(oauthidentity.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = &value
	}
	if value, ok := _c.mutation.Extra(); ok {
		_spec.SetField(oauthidentity.FieldExtra, field.TypeJSON, value)
		_node.Extra = value
	}
	if value, ok := _c.mutation.AuthorizedAt(); ok {
		_spec.SetField(oauthidentity.FieldAuthorizedAt, field.TypeTime, value)
		_node.AuthorizedAt = value
	}
	if value, ok := _c.mutation.BoundAt(); ok {
		_spec.SetField(oauthidentity.FieldBoundAt, field.TypeTime, value)
		_node.BoundAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OAuthIdentityCreateBulk is the builder for creating many OAuthIdentity entities in bulk.
type OAuthIdentityCreateBulk struct {
	config
	err      error
	builders []*OAuthIdentityCreate
}

// Save creates the OAuthIdentity entities in the database.
func (_c *OAuthIdentityCreateBulk) Save(ctx context.Context) ([]*OAuthIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthIdentityCreateBulk) SaveX(ctx context.Context) []*OAuthIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
