// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/oauthidentity"
	"card_manager/api_service/ent/refreshtoken"
	"card_manager/api_service/ent/schema"
	"card_manager/api_service/ent/smscode"
	"card_manager/api_service/ent/store"
	"card_manager/api_service/ent/storemember"
	"card_manager/api_service/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oauthidentityFields := schema.OAuthIdentity{}.Fields()
	_ = oauthidentityFields
	// oauthidentityDescProvider is the schema descriptor for provider field.
	oauthidentityDescProvider := oauthidentityFields[1].Descriptor()
	// oauthidentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	oauthidentity.ProviderValidator = func() func(string) error {
		validators := oauthidentityDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthidentityDescProviderUID is the schema descriptor for provider_uid field.
	oauthidentityDescProviderUID := oauthidentityFields[2].Descriptor()
	// oauthidentity.ProviderUIDValidator is a validator for the "provider_uid" field. It is called by the builders before save.
	oauthidentity.ProviderUIDValidator = func() func(string) error {
		validators := oauthidentityDescProviderUID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider_uid string) error {
			for _, fn := range fns {
				if err := fn(provider_uid); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthidentityDescUnionID is the schema descriptor for union_id field.
	oauthidentityDescUnionID := oauthidentityFields[3].Descriptor()
	// oauthidentity.UnionIDValidator is a validator for the "union_id" field. It is called by the builders before save.
	oauthidentity.UnionIDValidator = oauthidentityDescUnionID.Validators[0].(func(string) error)
	// oauthidentityDescUserID is the schema descriptor for user_id field.
	oauthidentityDescUserID := oauthidentityFields[4].Descriptor()
	// oauthidentity.DefaultUserID holds the default value on creation for the user_id field.
	oauthidentity.DefaultUserID = oauthidentityDescUserID.Default.(int64)
	// oauthidentityDescNickname is the schema descriptor for nickname field.
	oauthidentityDescNickname := oauthidentityFields[5].Descriptor()
	// oauthidentity.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	oauthidentity.NicknameValidator = oauthidentityDescNickname.Validators[0].(func(string) error)
	// oauthidentityDescAvatarURL is the schema descriptor for avatar_url field.
	oauthidentityDescAvatarURL := oauthidentityFields[6].Descriptor()
	// oauthidentity.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	oauthidentity.AvatarURLValidator = oauthidentityDescAvatarURL.Validators[0].(func(string) error)
	// oauthidentityDescAuthorizedAt is the schema descriptor for authorized_at field.
	oauthidentityDescAuthorizedAt := oauthidentityFields[8].Descriptor()
	// oauthidentity.DefaultAuthorizedAt holds the default value on creation for the authorized_at field.
	oauthidentity.DefaultAuthorizedAt = oauthidentityDescAuthorizedAt.Default.(func() time.Time)
	// oauthidentityDescCreatedAt is the schema descriptor for created_at field.
	oauthidentityDescCreatedAt := oauthidentityFields[10].Descriptor()
	// oauthidentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthidentity.DefaultCreatedAt = oauthidentityDescCreatedAt.Default.(func() time.Time)
	// oauthidentityDescUpdatedAt is the schema descriptor for updated_at field.
	oauthidentityDescUpdatedAt := oauthidentityFields[11].Descriptor()
	// oauthidentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthidentity.DefaultUpdatedAt = oauthidentityDescUpdatedAt.Default.(func() time.Time)
	// oauthidentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthidentity.UpdateDefaultUpdatedAt = oauthidentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescTokenHash is the schema descriptor for token_hash field.
	refreshtokenDescTokenHash := refreshtokenFields[2].Descriptor()
	// refreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	refreshtoken.TokenHashValidator = func() func(string) error {
		validators := refreshtokenDescTokenHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_hash string) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// refreshtokenDescDeviceID is the schema descriptor for device_id field.
	refreshtokenDescDeviceID := refreshtokenFields[5].Descriptor()
	// refreshtoken.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	refreshtoken.DeviceIDValidator = refreshtokenDescDeviceID.Validators[0].(func(string) error)
	// refreshtokenDescUserAgent is the schema descriptor for user_agent field.
	refreshtokenDescUserAgent := refreshtokenFields[6].Descriptor()
	// refreshtoken.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	refreshtoken.UserAgentValidator = refreshtokenDescUserAgent.Validators[0].(func(string) error)
	// refreshtokenDescIP is the schema descriptor for ip field.
	refreshtokenDescIP := refreshtokenFields[7].Descriptor()
	// refreshtoken.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	refreshtoken.IPValidator = refreshtokenDescIP.Validators[0].(func(string) error)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[8].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	smscodeFields := schema.SmsCode{}.Fields()
	_ = smscodeFields
	// smscodeDescPhone is the schema descriptor for phone field.
	smscodeDescPhone := smscodeFields[1].Descriptor()
	// smscode.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	smscode.PhoneValidator = func() func(string) error {
		validators := smscodeDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// smscodeDescScene is the schema descriptor for scene field.
	smscodeDescScene := smscodeFields[2].Descriptor()
	// smscode.SceneValidator is a validator for the "scene" field. It is called by the builders before save.
	smscode.SceneValidator = func() func(string) error {
		validators := smscodeDescScene.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scene string) error {
			for _, fn := range fns {
				if err := fn(scene); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// smscodeDescCodeHash is the schema descriptor for code_hash field.
	smscodeDescCodeHash := smscodeFields[3].Descriptor()
	// smscode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	smscode.CodeHashValidator = func() func(string) error {
		validators := smscodeDescCodeHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code_hash string) error {
			for _, fn := range fns {
				if err := fn(code_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// smscodeDescCreatedAt is the schema descriptor for created_at field.
	smscodeDescCreatedAt := smscodeFields[6].Descriptor()
	// smscode.DefaultCreatedAt holds the default value on creation for the created_at field.
	smscode.DefaultCreatedAt = smscodeDescCreatedAt.Default.(func() time.Time)
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescName is the schema descriptor for name field.
	storeDescName := storeFields[1].Descriptor()
	// store.NameValidator is a validator for the "name" field. It is called by the builders before save.
	store.NameValidator = func() func(string) error {
		validators := storeDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// storeDescCity is the schema descriptor for city field.
	storeDescCity := storeFields[2].Descriptor()
	// store.CityValidator is a validator for the "city" field. It is called by the builders before save.
	store.CityValidator = func() func(string) error {
		validators := storeDescCity.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(city string) error {
			for _, fn := range fns {
				if err := fn(city); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// storeDescAddress is the schema descriptor for address field.
	storeDescAddress := storeFields[3].Descriptor()
	// store.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	store.AddressValidator = storeDescAddress.Validators[0].(func(string) error)
	// storeDescOpenTime is the schema descriptor for open_time field.
	storeDescOpenTime := storeFields[4].Descriptor()
	// store.OpenTimeValidator is a validator for the "open_time" field. It is called by the builders before save.
	store.OpenTimeValidator = func() func(string) error {
		validators := storeDescOpenTime.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(open_time string) error {
			for _, fn := range fns {
				if err := fn(open_time); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// storeDescCloseTime is the schema descriptor for close_time field.
	storeDescCloseTime := storeFields[5].Descriptor()
	// store.CloseTimeValidator is a validator for the "close_time" field. It is called by the builders before save.
	store.CloseTimeValidator = func() func(string) error {
		validators := storeDescCloseTime.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(close_time string) error {
			for _, fn := range fns {
				if err := fn(close_time); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// storeDescBizType is the schema descriptor for biz_type field.
	storeDescBizType := storeFields[6].Descriptor()
	// store.BizTypeValidator is a validator for the "biz_type" field. It is called by the builders before save.
	store.BizTypeValidator = storeDescBizType.Validators[0].(func(string) error)
	// storeDescInviteCode is the schema descriptor for invite_code field.
	storeDescInviteCode := storeFields[7].Descriptor()
	// store.InviteCodeValidator is a validator for the "invite_code" field. It is called by the builders before save.
	store.InviteCodeValidator = func() func(string) error {
		validators := storeDescInviteCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(invite_code string) error {
			for _, fn := range fns {
				if err := fn(invite_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// storeDescStatus is the schema descriptor for status field.
	storeDescStatus := storeFields[9].Descriptor()
	// store.DefaultStatus holds the default value on creation for the status field.
	store.DefaultStatus = storeDescStatus.Default.(int8)
	// storeDescCreatedAt is the schema descriptor for created_at field.
	storeDescCreatedAt := storeFields[10].Descriptor()
	// store.DefaultCreatedAt holds the default value on creation for the created_at field.
	store.DefaultCreatedAt = storeDescCreatedAt.Default.(func() time.Time)
	// storeDescUpdatedAt is the schema descriptor for updated_at field.
	storeDescUpdatedAt := storeFields[11].Descriptor()
	// store.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	store.DefaultUpdatedAt = storeDescUpdatedAt.Default.(func() time.Time)
	// store.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	store.UpdateDefaultUpdatedAt = storeDescUpdatedAt.UpdateDefault.(func() time.Time)
	storememberFields := schema.StoreMember{}.Fields()
	_ = storememberFields
	// storememberDescRole is the schema descriptor for role field.
	storememberDescRole := storememberFields[3].Descriptor()
	// storemember.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	storemember.RoleValidator = func() func(string) error {
		validators := storememberDescRole.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(role string) error {
			for _, fn := range fns {
				if err := fn(role); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// storememberDescStatus is the schema descriptor for status field.
	storememberDescStatus := storememberFields[4].Descriptor()
	// storemember.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	storemember.StatusValidator = func() func(string) error {
		validators := storememberDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// storememberDescDisplayName is the schema descriptor for display_name field.
	storememberDescDisplayName := storememberFields[5].Descriptor()
	// storemember.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	storemember.DisplayNameValidator = storememberDescDisplayName.Validators[0].(func(string) error)
	// storememberDescCreatedAt is the schema descriptor for created_at field.
	storememberDescCreatedAt := storememberFields[7].Descriptor()
	// storemember.DefaultCreatedAt holds the default value on creation for the created_at field.
	storemember.DefaultCreatedAt = storememberDescCreatedAt.Default.(func() time.Time)
	// storememberDescUpdatedAt is the schema descriptor for updated_at field.
	storememberDescUpdatedAt := storememberFields[8].Descriptor()
	// storemember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storemember.DefaultUpdatedAt = storememberDescUpdatedAt.Default.(func() time.Time)
	// storemember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storemember.UpdateDefaultUpdatedAt = storememberDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[1].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = func() func(string) error {
		validators := userDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[3].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int8)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
