// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/store"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreCreate is the builder for creating a Store entity.
type StoreCreate struct {
	config
	mutation *StoreMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *StoreCreate) SetName(v string) *StoreCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *StoreCreate) SetCity(v string) *StoreCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *StoreCreate) SetAddress(v string) *StoreCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *StoreCreate) SetNillableAddress(v *string) *StoreCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetOpenTime sets the "open_time" field.
func (_c *StoreCreate) SetOpenTime(v string) *StoreCreate {
	_c.mutation.SetOpenTime(v)
	return _c
}

// SetCloseTime sets the "close_time" field.
func (_c *StoreCreate) SetCloseTime(v string) *StoreCreate {
	_c.mutation.SetCloseTime(v)
	return _c
}

// SetBizType sets the "biz_type" field.
func (_c *StoreCreate) SetBizType(v string) *StoreCreate {
	_c.mutation.SetBizType(v)
	return _c
}

// SetNillableBizType sets the "biz_type" field if the given value is not nil.
func (_c *StoreCreate) SetNillableBizType(v *string) *StoreCreate {
	if v != nil {
		_c.SetBizType(*v)
	}
	return _c
}

// SetInviteCode sets the "invite_code" field.
func (_c *StoreCreate) SetInviteCode(v string) *StoreCreate {
	_c.mutation.SetInviteCode(v)
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *StoreCreate) SetOwnerUserID(v int64) *StoreCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StoreCreate) SetStatus(v int8) *StoreCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StoreCreate) SetNillableStatus(v *int8) *StoreCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StoreCreate) SetCreatedAt(v time.Time) *StoreCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StoreCreate) SetNillableCreatedAt(v *time.Time) *StoreCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StoreCreate) SetUpdatedAt(v time.Time) *StoreCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StoreCreate) SetNillableUpdatedAt(v *time.Time) *StoreCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StoreCreate) SetID(v int64) *StoreCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the StoreMutation object of the builder.
func (_c *StoreCreate) Mutation() *StoreMutation {
	return _c.mutation
}

// Save creates the Store in the database.
func (_c *StoreCreate) Save(ctx context.Context) (*Store, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StoreCreate) SaveX(ctx context.Context) *Store {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StoreCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := store.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := store.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := store.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StoreCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Store.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Store.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := store.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Store.city": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := store.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Store.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpenTime(); !ok {
		return &ValidationError{Name: "open_time", err: errors.New(`ent: missing required field "Store.open_time"`)}
	}
	if v, ok := _c.mutation.OpenTime(); ok {
		if err := store.OpenTimeValidator(v); err != nil {
			return &ValidationError{Name: "open_time", err: fmt.Errorf(`ent: validator failed for field "Store.open_time": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CloseTime(); !ok {
		return &ValidationError{Name: "close_time", err: errors.New(`ent: missing required field "Store.close_time"`)}
	}
	if v, ok := _c.mutation.CloseTime(); ok {
		if err := store.CloseTimeValidator(v); err != nil {
			return &ValidationError{Name: "close_time", err: fmt.Errorf(`ent: validator failed for field "Store.close_time": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BizType(); ok {
		if err := store.BizTypeValidator(v); err != nil {
			return &ValidationError{Name: "biz_type", err: fmt.Errorf(`ent: validator failed for field "Store.biz_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InviteCode(); !ok {
		return &ValidationError{Name: "invite_code", err: errors.New(`ent: missing required field "Store.invite_code"`)}
	}
	if v, ok := _c.mutation.InviteCode(); ok {
		if err := store.InviteCodeValidator(v); err != nil {
			return &ValidationError{Name: "invite_code", err: fmt.Errorf(`ent: validator failed for field "Store.invite_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Store.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Store.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Store.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Store.updated_at"`)}
	}
	return nil
}

func (_c *StoreCreate) sqlSave(ctx context.Context) (*Store, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StoreCreate) createSpec() (*Store, *sqlgraph.CreateSpec) {
	var (
		_node = &Store{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(store.Table, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(store.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
		_node.Address = &value
	}
	if value, ok := _c.mutation.OpenTime(); ok {
		_spec.SetField(store.FieldOpenTime, field.TypeString, value)
		_node.OpenTime = value
	}
	if value, ok := _c.mutation.CloseTime(); ok {
		_spec.SetField(store.FieldCloseTime, field.TypeString, value)
		_node.CloseTime = value
	}
	if value, ok := _c.mutation.BizType(); ok {
		_spec.SetField(store.FieldBizType, field.TypeString, value)
		_node.BizType = &value
	}
	if value, ok := _c.mutation.InviteCode(); ok {
		_spec.SetField(store.FieldInviteCode, field.TypeString, value)
		_node.InviteCode = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(store.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(store.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(store.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(store.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// StoreCreateBulk is the builder for creating many Store entities in bulk.
type StoreCreateBulk struct {
	config
	err      error
	builders []*StoreCreate
}

// Save creates the Store entities in the database.
func (_c *StoreCreateBulk) Save(ctx context.Context) ([]*Store, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Store, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StoreCreateBulk) SaveX(ctx context.Context) []*Store {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
