// Code generated by ent, DO NOT EDIT.

package ent

import (
	"card_manager/api_service/ent/predicate"
	"card_manager/api_service/ent/storenotifysetting"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreNotifySettingUpdate is the builder for updating StoreNotifySetting entities.
type StoreNotifySettingUpdate struct {
	config
	hooks    []Hook
	mutation *StoreNotifySettingMutation
}

// Where appends a list predicates to the StoreNotifySettingUpdate builder.
func (_u *StoreNotifySettingUpdate) Where(ps ...predicate.StoreNotifySetting) *StoreNotifySettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *StoreNotifySettingUpdate) SetStoreID(v int64) *StoreNotifySettingUpdate {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *StoreNotifySettingUpdate) SetNillableStoreID(v *int64) *StoreNotifySettingUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *StoreNotifySettingUpdate) AddStoreID(v int64) *StoreNotifySettingUpdate {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetEvent sets the "event" field.
func (_u *StoreNotifySettingUpdate) SetEvent(v string) *StoreNotifySettingUpdate {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *StoreNotifySettingUpdate) SetNillableEvent(v *string) *StoreNotifySettingUpdate {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *StoreNotifySettingUpdate) SetEnabled(v bool) *StoreNotifySettingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *StoreNotifySettingUpdate) SetNillableEnabled(v *bool) *StoreNotifySettingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotifyBoss sets the "notify_boss" field.
func (_u *StoreNotifySettingUpdate) SetNotifyBoss(v bool) *StoreNotifySettingUpdate {
	_u.mutation.SetNotifyBoss(v)
	return _u
}

// SetNillableNotifyBoss sets the "notify_boss" field if the given value is not nil.
func (_u *StoreNotifySettingUpdate) SetNillableNotifyBoss(v *bool) *StoreNotifySettingUpdate {
	if v != nil {
		_u.SetNotifyBoss(*v)
	}
	return _u
}

// SetWechat sets the "wechat" field.
func (_u *StoreNotifySettingUpdate) SetWechat(v bool) *StoreNotifySettingUpdate {
	_u.mutation.SetWechat(v)
	return _u
}

// SetNillableWechat sets the "wechat" field if the given value is not nil.
func (_u *StoreNotifySettingUpdate) SetNillableWechat(v *bool) *StoreNotifySettingUpdate {
	if v != nil {
		_u.SetWechat(*v)
	}
	return _u
}

// SetApp sets the "app" field.
func (_u *StoreNotifySettingUpdate) SetApp(v bool) *StoreNotifySettingUpdate {
	_u.mutation.SetApp(v)
	return _u
}

// SetNillableApp sets the "app" field if the given value is not nil.
func (_u *StoreNotifySettingUpdate) SetNillableApp(v *bool) *StoreNotifySettingUpdate {
	if v != nil {
		_u.SetApp(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StoreNotifySettingUpdate) SetUpdatedAt(v time.Time) *StoreNotifySettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StoreNotifySettingMutation object of the builder.
func (_u *StoreNotifySettingUpdate) Mutation() *StoreNotifySettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StoreNotifySettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreNotifySettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StoreNotifySettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreNotifySettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StoreNotifySettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storenotifysetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StoreNotifySettingUpdate) check() error {
	if v, ok := _u.mutation.Event(); ok {
		if err := storenotifysetting.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "StoreNotifySetting.event": %w`, err)}
		}
	}
	return nil
}

func (_u *StoreNotifySettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storenotifysetting.Table, storenotifysetting.Columns, sqlgraph.NewFieldSpec(storenotifysetting.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(storenotifysetting.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(storenotifysetting.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(storenotifysetting.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(storenotifysetting.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyBoss(); ok {
		_spec.SetField(storenotifysetting.FieldNotifyBoss, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Wechat(); ok {
		_spec.SetField(storenotifysetting.FieldWechat, field.TypeBool, value)
	}
	if value, ok := _u.mutation.App(); ok {
		_spec.SetField(storenotifysetting.FieldApp, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storenotifysetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storenotifysetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StoreNotifySettingUpdateOne is the builder for updating a single StoreNotifySetting entity.
type StoreNotifySettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StoreNotifySettingMutation
}

// SetStoreID sets the "store_id" field.
func (_u *StoreNotifySettingUpdateOne) SetStoreID(v int64) *StoreNotifySettingUpdateOne {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *StoreNotifySettingUpdateOne) SetNillableStoreID(v *int64) *StoreNotifySettingUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *StoreNotifySettingUpdateOne) AddStoreID(v int64) *StoreNotifySettingUpdateOne {
	_u.mutation.AddStoreID(v)
	return _u
}

// SetEvent sets the "event" field.
func (_u *StoreNotifySettingUpdateOne) SetEvent(v string) *StoreNotifySettingUpdateOne {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *StoreNotifySettingUpdateOne) SetNillableEvent(v *string) *StoreNotifySettingUpdateOne {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *StoreNotifySettingUpdateOne) SetEnabled(v bool) *StoreNotifySettingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *StoreNotifySettingUpdateOne) SetNillableEnabled(v *bool) *StoreNotifySettingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotifyBoss sets the "notify_boss" field.
func (_u *StoreNotifySettingUpdateOne) SetNotifyBoss(v bool) *StoreNotifySettingUpdateOne {
	_u.mutation.SetNotifyBoss(v)
	return _u
}

// SetNillableNotifyBoss sets the "notify_boss" field if the given value is not nil.
func (_u *StoreNotifySettingUpdateOne) SetNillableNotifyBoss(v *bool) *StoreNotifySettingUpdateOne {
	if v != nil {
		_u.SetNotifyBoss(*v)
	}
	return _u
}

// SetWechat sets the "wechat" field.
func (_u *StoreNotifySettingUpdateOne) SetWechat(v bool) *StoreNotifySettingUpdateOne {
	_u.mutation.SetWechat(v)
	return _u
}

// SetNillableWechat sets the "wechat" field if the given value is not nil.
func (_u *StoreNotifySettingUpdateOne) SetNillableWechat(v *bool) *StoreNotifySettingUpdateOne {
	if v != nil {
		_u.SetWechat(*v)
	}
	return _u
}

// SetApp sets the "app" field.
func (_u *StoreNotifySettingUpdateOne) SetApp(v bool) *StoreNotifySettingUpdateOne {
	_u.mutation.SetApp(v)
	return _u
}

// SetNillableApp sets the "app" field if the given value is not nil.
func (_u *StoreNotifySettingUpdateOne) SetNillableApp(v *bool) *StoreNotifySettingUpdateOne {
	if v != nil {
		_u.SetApp(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StoreNotifySettingUpdateOne) SetUpdatedAt(v time.Time) *StoreNotifySettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StoreNotifySettingMutation object of the builder.
func (_u *StoreNotifySettingUpdateOne) Mutation() *StoreNotifySettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the StoreNotifySettingUpdate builder.
func (_u *StoreNotifySettingUpdateOne) Where(ps ...predicate.StoreNotifySetting) *StoreNotifySettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StoreNotifySettingUpdateOne) Select(field string, fields ...string) *StoreNotifySettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StoreNotifySetting entity.
func (_u *StoreNotifySettingUpdateOne) Save(ctx context.Context) (*StoreNotifySetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreNotifySettingUpdateOne) SaveX(ctx context.Context) *StoreNotifySetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StoreNotifySettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreNotifySettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StoreNotifySettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storenotifysetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StoreNotifySettingUpdateOne) check() error {
	if v, ok := _u.mutation.Event(); ok {
		if err := storenotifysetting.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "StoreNotifySetting.event": %w`, err)}
		}
	}
	return nil
}

func (_u *StoreNotifySettingUpdateOne) sqlSave(ctx context.Context) (_node *StoreNotifySetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storenotifysetting.Table, storenotifysetting.Columns, sqlgraph.NewFieldSpec(storenotifysetting.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StoreNotifySetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storenotifysetting.FieldID)
		for _, f := range fields {
			if !storenotifysetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storenotifysetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(storenotifysetting.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(storenotifysetting.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(storenotifysetting.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(storenotifysetting.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyBoss(); ok {
		_spec.SetField(storenotifysetting.FieldNotifyBoss, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Wechat(); ok {
		_spec.SetField(storenotifysetting.FieldWechat, field.TypeBool, value)
	}
	if value, ok := _u.mutation.App(); ok {
		_spec.SetField(storenotifysetting.FieldApp, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storenotifysetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &StoreNotifySetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storenotifysetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
