// Code generated by ent, DO NOT EDIT.

package storenotifysetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the storenotifysetting type in the database.
	Label = "store_notify_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStoreID holds the string denoting the store_id field in the database.
	FieldStoreID = "store_id"
	// FieldEvent holds the string denoting the event field in the database.
	FieldEvent = "event"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldNotifyBoss holds the string denoting the notify_boss field in the database.
	FieldNotifyBoss = "notify_boss"
	// FieldWechat holds the string denoting the wechat field in the database.
	FieldWechat = "wechat"
	// FieldApp holds the string denoting the app field in the database.
	FieldApp = "app"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the storenotifysetting in the database.
	Table = "store_notify_settings"
)

// Columns holds all SQL columns for storenotifysetting fields.
var Columns = []string{
	FieldID,
	FieldStoreID,
	FieldEvent,
	FieldEnabled,
	FieldNotifyBoss,
	FieldWechat,
	FieldApp,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventValidator is a validator for the "event" field. It is called by the builders before save.
	EventValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultNotifyBoss holds the default value on creation for the "notify_boss" field.
	DefaultNotifyBoss bool
	// DefaultWechat holds the default value on creation for the "wechat" field.
	DefaultWechat bool
	// DefaultApp holds the default value on creation for the "app" field.
	DefaultApp bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the StoreNotifySetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStoreID orders the results by the store_id field.
func ByStoreID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreID, opts...).ToFunc()
}

// ByEvent orders the results by the event field.
func ByEvent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvent, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByNotifyBoss orders the results by the notify_boss field.
func ByNotifyBoss(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyBoss, opts...).ToFunc()
}

// ByWechat orders the results by the wechat field.
func ByWechat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWechat, opts...).ToFunc()
}

// ByApp orders the results by the app field.
func ByApp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApp, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
