// Code generated by ent, DO NOT EDIT.

package storenotifysetting

import (
	"card_manager/api_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLTE(FieldID, id))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldStoreID, v))
}

// Event applies equality check predicate on the "event" field. It's identical to EventEQ.
func Event(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldEvent, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldEnabled, v))
}

// NotifyBoss applies equality check predicate on the "notify_boss" field. It's identical to NotifyBossEQ.
func NotifyBoss(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldNotifyBoss, v))
}

// Wechat applies equality check predicate on the "wechat" field. It's identical to WechatEQ.
func Wechat(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldWechat, v))
}

// App applies equality check predicate on the "app" field. It's identical to AppEQ.
func App(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldApp, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNotIn(FieldStoreID, vs...))
}

// StoreIDGT applies the GT predicate on the "store_id" field.
func StoreIDGT(v int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGT(FieldStoreID, v))
}

// StoreIDGTE applies the GTE predicate on the "store_id" field.
func StoreIDGTE(v int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGTE(FieldStoreID, v))
}

// StoreIDLT applies the LT predicate on the "store_id" field.
func StoreIDLT(v int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLT(FieldStoreID, v))
}

// StoreIDLTE applies the LTE predicate on the "store_id" field.
func StoreIDLTE(v int64) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLTE(FieldStoreID, v))
}

// EventEQ applies the EQ predicate on the "event" field.
func EventEQ(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldEvent, v))
}

// EventNEQ applies the NEQ predicate on the "event" field.
func EventNEQ(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldEvent, v))
}

// EventIn applies the In predicate on the "event" field.
func EventIn(vs ...string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldIn(FieldEvent, vs...))
}

// EventNotIn applies the NotIn predicate on the "event" field.
func EventNotIn(vs ...string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNotIn(FieldEvent, vs...))
}

// EventGT applies the GT predicate on the "event" field.
func EventGT(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGT(FieldEvent, v))
}

// EventGTE applies the GTE predicate on the "event" field.
func EventGTE(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGTE(FieldEvent, v))
}

// EventLT applies the LT predicate on the "event" field.
func EventLT(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLT(FieldEvent, v))
}

// EventLTE applies the LTE predicate on the "event" field.
func EventLTE(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLTE(FieldEvent, v))
}

// EventContains applies the Contains predicate on the "event" field.
func EventContains(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldContains(FieldEvent, v))
}

// EventHasPrefix applies the HasPrefix predicate on the "event" field.
func EventHasPrefix(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldHasPrefix(FieldEvent, v))
}

// EventHasSuffix applies the HasSuffix predicate on the "event" field.
func EventHasSuffix(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldHasSuffix(FieldEvent, v))
}

// EventEqualFold applies the EqualFold predicate on the "event" field.
func EventEqualFold(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEqualFold(FieldEvent, v))
}

// EventContainsFold applies the ContainsFold predicate on the "event" field.
func EventContainsFold(v string) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldContainsFold(FieldEvent, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldEnabled, v))
}

// NotifyBossEQ applies the EQ predicate on the "notify_boss" field.
func NotifyBossEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldNotifyBoss, v))
}

// NotifyBossNEQ applies the NEQ predicate on the "notify_boss" field.
func NotifyBossNEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldNotifyBoss, v))
}

// WechatEQ applies the EQ predicate on the "wechat" field.
func WechatEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldWechat, v))
}

// WechatNEQ applies the NEQ predicate on the "wechat" field.
func WechatNEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldWechat, v))
}

// AppEQ applies the EQ predicate on the "app" field.
func AppEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldApp, v))
}

// AppNEQ applies the NEQ predicate on the "app" field.
func AppNEQ(v bool) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldApp, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StoreNotifySetting) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StoreNotifySetting) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StoreNotifySetting) predicate.StoreNotifySetting {
	return predicate.StoreNotifySetting(sql.NotPredicates(p))
}
